### ISSUE TITLE
[BUG] Relax and Tweak tool is invisible and unusable

### ISSUE THREAD

**Issue by Aravius** [CGCookie/retopoflow#1055]
-----------------------------------

---

Retopoflow Version: 3.2.4

Blender Version/Hash: 2.93.5

**Issue:**

Hello. For a few weeks ive had a issue with Retopoflow. Whenever i try to use Relax and Tweak both tools are invisible and cant be used. I can adjust both strength and size on both brushes but as soon as i set size / strength the circle icon disappears.

I have tried to look for solutions but so far ive found nothing. Please help and this bug makes the program almost useless. Im not aware of how to replicate this bug, as im not sure what I have done to break the program. 

I have tried to reinstall retopoflow without it changing anything.

Kind regards, Robin 

EDIT: Ive been trying to troubleshot some more and made some progress.

When i reset all settings to default everything seems to be working, but the clipping is bugged so I turn off "Override with fixed values", so far so good. Now the problem is the "Normal offset" set to 1 makes the mesh messed up and it looks like it exploded. I set this to 0 and everything breaks. I cant select any vertecies. So now i disable "Block occuluded" and "Block backface" and i can click vertecies again, but now the "Relax" and "Tweak" tools cant be used. Now i can see the tools ( I didnt before ) but they dont affect vertecies at all. Getting really frustraded with Retopoflow now, every time i fix one issues several more appears. 

I also tried to delete any files related to Retopflow from my computer before reinstalling, no difference.

EDIT #2

Tried to delete all Retopoflow files from computer and install a previous version ( 3.22 ). This version just crashes as soon as i try to start it. Error log:

Environment:

- RetopoFlow: 3.2.2
- Blender: 2.93.5 master 2021-10-05
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 471.96, 4.50 NVIDIA
- Timestamp: 2021-11-13 03:27:11.786295
- Undo: 

Error Hash: d1282c452d548cc71720b88cf419b5d9

Trace:
```
EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow_LastTool' object has no attribute 'rftool'
C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy_types.py
000 0728:__getattribute__() return super().__getattribute__(attr)
C:\Users\Robin\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\CGCookie-retopoflow-fc1e169\retopoflow\rf\rf_states.py
001 0176:modal_main() if self.rftool._fsm.state == 'main' and (not self.rftool.rfwidget or self.rftool.rfwidget._fsm.state == 'main'):
.../common\fsm.py
002 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report and the updates, @Aravius! will take a look as soon as I can. any chance you can share this .blend file (or another one that causes this issue) with us so we can reproduce this on our machines? you can email it to retopoflow@cgcookie.com. thanks!

**Comment by vxlcoder** [comment]
I'm trying to replicate your issue, @Aravius, but I'm not sure how your .blend file is set up to cause your original and edit 1 issues.  Are you able to replicate this issue with the default scene, or does it only happen on a specific .blend file?  Again, if you can, please send us a .blend file via retopoflow@cgcookie.com that causes this issue on your machine.

Regarding your edit 2 report where RF crashes, this is likely due to something breaking when RF is starting up (and unfortunately not reported to you in the Blender window), which then causes a cascade of other issues.  One thing that would be helpful for debugging is to copy-paste everything that is written to the system console, as almost all errors are reported there.  To do this on your Windows machine, start Blender as usual, then click Window > Toggle System Console ([link](https://docs.blender.org/manual/en/2.79/advanced/command_line/introduction.html)) to open up another window with a bunch of text.  Then back in Blender, try starting RF (which will crash).  Finally, copy-paste everything from the system console window here.  Note: you might need to scroll if there is a lot of text.

Thank you for your help in debugging these issues!  We will do what we can to fix these issues and get you back to retopologizing!

**Comment by jfranmatheu** [comment]
After careful review, this issue is being closed due to prolonged inactivity. Despite later attempts to gather more details about the reported problem, no further response has been received from the original reporter. 

If additional information becomes available and the issue persist in latest RetopoFlow version, the issue can be reopened for further investigation.
