### ISSUE TITLE
[Features] Save RF backup files with WIP models only

### ISSUE THREAD

**Issue by LLKoder** [CGCookie/retopoflow#1057]
There is possible to save backup RF file with WIP model only?

I explain what I mean.

I have 5GB my project file with more than 15 models.
When I do retopology RF create new backup file with whole models (then I have two files at 5GB each - project and RF backup), while I use two models only (high and low).
There is redundant storage size and spend more time for saving.

Sure I would able to do my work in separate file for this case but it don't suit me.

There is possible to save backup RF file with current models - high resolution and low resolution models only (WIP models)?

Thanks in advance.

**Comment by vxlcoder** [comment]
Thanks for the Feature request, @LLKoder.

RetopoFlow's backup uses Blender's save functionality and Blender's auto-save options.  This means that if you have auto-save enabled in Blender (Edit > Preferences > Save & Load > Blend Files > Auto Save), then RetopoFlow will write backup files at the same interval that is set in those preferences.  Also, to make the backup, RetopoFlow uses Blender's save directly.  So, RetopoFlow is basically doing exactly the same thing that Blender does (when saving or auto-saving).

We could try to write some complicated code to try to save only the part of mesh that is currently worked on, but honestly that's beyond the scope of what RetopoFlow _should_ do.  (If Blender added this functionality, we could use it, though)

You have a few options:

1. (**NOT RECOMMENDED**) Turn off Auto Save.  This would prevent RF from automatically saving at the interval set in Blender preferences.  You can still `Ctrl+S` to save the file while in RF even with auto save turned off.  However, if something bad happened and Blender crashes, you will only be able to recover since the last time you remembered to save.
2. (**NOT RECOMMENDED**) Increase the auto save Timer so it saves less often.  Same as above, but at least auto save is still happening even if you don't remember to `Ctrl+S`.
3. (**RECOMMENDED**) Create a new Blend file, link (_not_ append) in the large meshes, and create the low poly mesh in that file.  This would make the file you are working on only as big as the low poly version.

Please let us know if you have any other questions!

Happy retopo'ing!

**Comment by vxlcoder** [comment]
closing this issue, but feel free to post follow-up questions.

Thanks again for reaching out!
