### ISSUE TITLE
**[BUG]** Can't place vertices or they snap to random point midair

### ISSUE THREAD

**Issue by itsrosfox** [CGCookie/retopoflow#1062]
Retopoflow Version: 3.2.5

Blender Version/Hash: 3.0.0

Platform Version/Distribution: Windows 10 Pro 21H1 (19043.1348)

&nbsp;

**Issue:**

When trying to place vertices on my body with the PolyPen tool they always get placed into a random point in-air. I worked on the model the previous day and it worked fine. Now it stopped working and even creating new retopo meshes doesn't seem to help it.

![Bug gif](https://user-images.githubusercontent.com/95133420/145681403-4601d9e3-33b6-4aea-bdbf-2bb15325d6cc.gif)

&nbsp;

**How to Reproduce:**

- Select poly tool
- Try place new vertices

[Blend file](https://github.com/CGCookie/retopoflow/files/7697252/Issue.zip)

**Comment by vxlcoder** [comment]
thanks for the report, @itsrosfox.

I am not sure what's happening here, but I will take a look as soon as I can.

**Comment by itsrosfox** [comment]
understandable, thank you for such a quick response!

**Comment by vxlcoder** [comment]
Thanks again for the report and the blend file, @itsrosfox!

This is a very strange error, but I was able to fix it.

The raycast code (either in Blender or in my wrapper code) was detecting that the mouse is over different objects rather than the body.  I'm not entirely sure why at the moment, but it's easy to detect when it is incorrect.

Commit 108c703 detects these errors, and now RF handles it correctly.  You can try it out using the updater system ([doc](https://docs.retopoflow.com/addon_updater.html)).  Just use `v3.2.6` or `108c703` in the `Advanced: Commit / Branch` textbox.

Please let us know if you have any other issues.

Happy Retopo'ing!

**Comment by itsrosfox** [comment]
I installed commit 108c703 and can confirm that the issue is now fixed for my case. Thanks!

**Comment by vxlcoder** [comment]
Glad to hear!  closing this issue.
