### ISSUE TITLE
how to show model's texture when undering  retopoflow?

### ISSUE THREAD

**Issue by flashice2030** [CGCookie/retopoflow#1082]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Hi, @flashice2030.

Sorry for the delay in reply.

In order to show the texture on the source meshes while using RetopoFlow, choose Options > Viewport Display > Optimize Shading > Off.

<img width="716" alt="Screen Shot 2022-03-04 at 10 59 22 AM" src="https://user-images.githubusercontent.com/3790699/156816928-5d805089-2dc5-4e5e-89e9-feceb7515d76.png">

Closing for now, but please let us know if you have any other questions!
