### ISSUE TITLE
why does the geometry collapse after exposure to the relax, tweak, poly strips tool

### ISSUE THREAD

**Issue by Arturiusd** [CGCookie/retopoflow#1084]
question about **Retopoflow**
why does the geometry collapse after exposure to the relax, tweak, poly strips tool
it's just that when moving geometry in symmetry mode, this geometry immediately collapses in the center.
but without symmetry it works fine

made a screenshot:
https://b.radikal.ru/b21/2202/de/60f9309bca90.jpg
https://a.radikal.ru/a40/2202/bd/8771530833e5.jpg

**Comment by vxlcoder** [comment]
Hi @Arturiusd.

It looks like maybe you have geometry on the mirror side.  If that's the case, then some of the tools will snap the vertices on the mirrored side to the mirror plane (the center line of mirroring).  Try this: in Edit Mode, select all the verts, then hit `S` to scale, hit `X` to scale only along x-axis (or use `Y` if you're mirroring along y-axis instead), then type `-1` and hit enter.  After that, try going back into RetopoFlow to see if everything works as expected.

Let me know whether that works for you or not.  And if not, please also let us know what version of RetopoFlow you're using, and maybe consider sending us your .blend file so that we can take a closer look.  You can send it to retopoflow@cgcookie.com if you don't want to post it here.

thanks!

**Comment by Arturiusd** [comment]
> Привет @Arturiusd .
> 
> Похоже, у вас есть геометрия на зеркальной стороне. Если это так, то некоторые инструменты будут привязывать вершины на зеркальной стороне к зеркальной плоскости (центральной линии зеркального отображения). Попробуйте следующее: в режиме редактирования выберите все вершины, затем нажмите `S`, чтобы масштабировать, нажмите, `X`чтобы масштабировать только по оси X (или используйте `Y`, если вместо этого вы зеркально отражаете по оси Y), затем введите `-1`и нажмите Enter. После этого попробуйте вернуться в RetopoFlow, чтобы посмотреть, все ли работает как положено.
> 
> Дайте мне знать, работает ли это для вас или нет. А если нет, пожалуйста, сообщите нам, какую версию RetopoFlow вы используете, и, возможно, рассмотрите возможность отправки нам вашего файла .blend, чтобы мы могли рассмотреть его поближе. Вы можете отправить его по [адресу retopoflow@cgcookie.com](mailto:retopoflow@cgcookie.com) , если не хотите публиковать его здесь.
> 
> Благодарность!

I do not know what happened
but now it doesn't collapse in the center,
but I didn't change anything!

I have three vertices on the other side of the mesh, but they don't interfere with my work.
it just works

If this problem occurs again, I will write
thanks!

**Comment by vxlcoder** [comment]
I pushed commit 7d043c1 as a fix for issue #1089 that should give some hint for your issue here, @Arturiusd.

Closing this issue for now, but let us know if you still have this issue after updating to v3.2.6, either officially or through the Updater System ([doc](https://docs.retopoflow.com/addon_updater.html), branch `v3.2.6`).

happy retopo'ing!
