### ISSUE TITLE
If i exit the plugin and then go back, i will not be able to edit the content.

### ISSUE THREAD

**Issue by defawang4399** [CGCookie/retopoflow#1104]
Retopoflow Version: {*3.2.4*}

Blender Version/Hash: {*3.1*}

Platform Version/Distribution: {*windows/mac*}

**Issue:**

Hi, I'm new to plugins and I'm having these issues below.

QUESTION1, when I exit the plugin and go back to editing, I find that I can't move the existing points or lines or surfaces, and I can only continue editing if I optimize it with the "relax" tool;

QUESTION2, when I create a new topology, the symmetry tool is available, it can be turned on and let me move the points at will. When I enter the plugin for a second edit, the symmetry tool is not available, because when I move any point, this point will run to the symmetry line.

The above are my two questions, because I am a novice, I don't know if I have to enable any settings to avoid the above problems, I hope you can reply to me after seeing it, thank you very much.

**Comment by jlampel** [comment]
Hi, thank you for the report! 

For #1, are you saying that leaving and then returning to RetopoFlow results in only the Relax tool working? A video or example file would be really helpful here if you're willing to share since I can't replicate this. 

For #2, it sounds like maybe you rotated the object in edit mode or applied rotation in between RetopoFlow sessions? The RF symmetry works similar to the mirror modifier but a little different in that it mirrors the positive X and negative Y (what you see in front and side view) to their opposites. Working on the negative X or positive Y sides will cause the verts to snap to the symmetry line because those areas are controlled by the mirror. You can turn on Face visualization to get a sense of what side it expects you to work on. This may also solve question #1. 

Hope that helps!
