### ISSUE TITLE
**[QUESTION]** RetopoFlow will not enable - Syntax error

### ISSUE THREAD

**Issue by cinnaval** [CGCookie/retopoflow#1109]
Retopoflow Version: {Tried 2.0.3 and master zip}

Blender Version/Hash: {2.78}

Platform Version/Distribution: {Windows}

&nbsp;

**Issue:**

Hello! I am trying to install retopoflow to my blender and it will not enable. I tried downloading the master zip, renaming it to retopoflow and installing it but when I try to enable it I get a syntax error. I attached the error below. I have also tried downloading the 2.0.3 zip but that one will not even upload to blender. I tried looking t through the forum but I haven't seen anything that fixed my problem. Thank you in advance!

![Screenshot 2022-04-09 171002](https://user-images.githubusercontent.com/103308860/162595721-388198d4-6089-4443-8110-930846ab81ee.jpg)

&nbsp;

**Comment by vxlcoder** [comment]
Hi @cinnaval.

I don't think RF v2.0.3 will run in Blender 2.78.  Officially, RF v2.0.x requires at least Blender 2.79.  I'm going to see if I can possibly get Blender 2.78c to run on my machine to run a quick test, but you might have to use RF v1.3.2 for that old of Blender version.

Note: the latest version of RF requires at least Blender 3.0 due to some significant changes in Blender API and Blender's version of Python.

**Comment by vxlcoder** [comment]
My quick test shows that Blender 2.78 can at least start RetopoFlow 2.0.3.

You can download a zip from https://github.com/CGCookie/retopoflow/releases/tag/v2.0.3.  Just be sure to download and install the `retopoflow.zip` file and not one of the `Source code` versions.

Give that a go and let us know.
