### ISSUE TITLE
 **[BUG]** Disappearing mesh

### ISSUE THREAD

**Issue by jureAFX** [CGCookie/retopoflow#1124]
Retopoflow Version: v3.2.6

Blender Version/Hash: 3.1

Platform Version/Distribution: Win10

**Issue:**

Mesh just disappears after reopening retopoflow the next day to continue working. There are also no "orange" edges on the remaining mash to snap on. Also deleting faces (outer faces that remained) leaves vertices and edges behind (not like normal behavior when deleting faces).

One solution is to redo the mesh by deleting outer vertices and start to create new geometry...

![image](https://user-images.githubusercontent.com/106229864/170203679-fc49e95e-dd5d-4f0f-ac85-1e4c7f91df67.png)

Anyone with the same problem? Any idea how to solve this? 

Thanks for answers and best regards

**Comment by vxlcoder** [comment]
Hi, @jureAFX.

Thanks for the report.  To help us dig into this issue, I have a few questions:

- What do you mean by the "Mesh just disappears"?  Does the entire mesh disappear?   Or, is it only part of the mesh?  If part, is it only the boundary edges (edges that are adjacent to exactly 1 face), or wire edges (edges adjacent to 0 faces), or other?
- I'm not sure what the screenshot is trying to show.  Can you help me see what you're seeing?  Can you post a screenshot after making some changes, then close out of RF and Blender and restart Blender and RF (simulate the "reopening retopoflow the next day"), and post a screenshot of what you see then?  If possible, use selection to highlight the area of the mesh that's not correct (or will be incorrect after reopening), or you can edit the screenshot in an image editor to highlight. 
- Are you able to send us a .blend file so that we can take a closer look? 
- Are you able to replicate the behavior on the default cube (maybe after loading factory settings)?  Or does this only happen on this particular model?

**Comment by jureAFX** [comment]
Hello @vxlcoder 

I am sorry for the lack of information. I will do my best to try to explain what I am experiencing.

Part of the mesh disappears. From the screenshot, you can see that some parts are not meshed. Complete part was meshed.
It is not just boundary edges or wire edges. I can not determine what type of mesh has disappeared because it seems there is no defined type just random part of the mesh is gone. Another thing I have noticed is that if I exit RF end check RetopoFlow mesh in edit mode is the same as in RF but if I view it in object mode "phantom" mesh appears (mesh that is not visible in RF or edit mode)

![image](https://user-images.githubusercontent.com/106229864/170426876-10e7a03d-d596-4a25-b8e5-a7d9c64c7a5c.png)
This is in edit mode.
![image](https://user-images.githubusercontent.com/106229864/170426968-2b6a9d5f-2061-4add-954e-d60c218a19fe.png)
This is in object mode
![image](https://user-images.githubusercontent.com/106229864/170427065-5f7c5926-f594-4df5-9f43-872d8b2cbf89.png)
This is RF mode

I have tried to duplicate the problem but was not able to replicate this behavior. I will try to replicate this on a cube.

**Comment by jureAFX** [comment]
@vxlcoder 

That is it, you nailed it. This is exactly what happened. Some of the geometry was hidden. I do not know the exact reason for this. Maybe it was even my fault. I am glad you solved it. Thank you for all the help and quick responses.

Best regards.
