### ISSUE TITLE
[BUG] Annoying problems while working in RetopoFlow

### ISSUE THREAD

**Issue by German-S** [CGCookie/retopoflow#1131]
Retopoflow Version: 3.2.8
Blender Version/Hash: 3.1.2
Platform Version/Distribution: Window 11 21H2 22000.708

Hello.
I came across several unpleasant features that interfere with work:
1)When saving a scene while in RetopoFlow retopology mode, the camera moves spontaneously. Each time you have to manually return to the edited part.
2)Sometimes when canceling actions (Ctrl + Z ), the created retopology mesh disappears.

How to Reproduce:
1 - It is enough to open the saved scene, perform some manipulations in the RetopoFlow repotopolgy mode, and save (Ctrl + S).
2 - I did not manage to accurately reproduce the problem, but I had it when working with the PolyPen, Relax, Tweak tools.
To fix this problem, i have to exit the RetopoFlow retopology mode and start again.

These updates are related to the second question:
UPD 1: this problem is most often repeated when undoing actions while using these tools.
UPD 2: I noticed that the grid does not just disappear, it decreases in size and is located below, under the main mesh.

**Comment by jlampel** [comment]
Hi! It sounds like you're experiencing both issue #1130 and #1132. Thank you for reporting! We'll work through them in those threads if you'd like to follow along with the progress.

**Comment by German-S** [comment]
> Hi! It sounds like you're experiencing both issue #1130 and #1132. Thank you for reporting! We'll work through them in those threads if you'd like to follow along with the progress.


Guys, thanks to your plugin, I make cool things much easier, thanks for supporting and creating such a miracle for us)

Why don't you create two development branches for this plugin ?
Section 1: A stable, tested version with no issues.
Section 2: dev version, with new features and fixes, but still under testing.

This isn't the first time I've run into an update issue or a problematic plugin after an update.
I think it would be the right decision to keep the stable and dev version separately.
What do you think about this?

**Comment by vxlcoder** [comment]
We actually do follow a similar dev pattern, @German-S.  Our `master` branch is the (as-much-as-possible) stable version of RetopoFlow with tags indicating official releases.  Branches other than `master` (ex: `v3.2.8`, `v3.2.7`, ...) are our working branch in which development occurs.  Once we believe the dev branch is ready for release, we merge it into `master`, tag it, and create a release zip.  Since our more recent development involves relatively smaller / minor changes, we haven't used more complicated branching patterns (ex: new feature branches), so we have stuck to this basic pattern. 

Perhaps what might help us achieve more stability in the official releases is to return to tagging different stages of dev branches (alpha, beta, release candidate).  However, unless they are watching the GitHub repo with notifications enabled, we don't have a good way to notify current users of new pre-release versions, ones that _should_ be usable but may contain bugs and needs testing.  I'll suggest a feature to the Blender Market team and look more at the built-in updater system...

Thank you for the suggestion!  We appreciate the feedback.
