### ISSUE TITLE
Error when activating plugin in 2.74

### ISSUE THREAD

**Issue by Tian90** [CGCookie/retopoflow#114]
Hello, I'm getting this error 
![untitled-2](https://cloud.githubusercontent.com/assets/12463859/7658147/b867033a-fb2f-11e4-91d3-941d3c0a5750.jpg) when I'm trying to activate polystrips addon (version 1.0.2)
I am using Blender 2.74.
Any one know whats happening and how to fix this? 

Thank you in advance

**Comment by Tian90** [comment]
I got retopoflow and polystrips there won't work for me too... when I press polystrips this error shows up: 
![untitled-2](https://cloud.githubusercontent.com/assets/12463859/7662354/41f7e66e-fb53-11e4-8403-df9af3231a1b.jpg)

**Comment by lostinadaydream** [comment]
Took me quite a while to get to this solution but it appears this bug is related to Issue #99 in which PolyStrips does not work existing modifiers. I was able to work around this by simply applying all current modifiers to the mesh and then activating the PolyStrips tool. This definitely will not be the preferred solution for users with high levels of subdivision but at least it works until the next SW update.

**Comment by carter2422** [comment]
Sorry about the late reply @Tian90 and @lostinadaydream. 

@Tian90 were you able to test whether applying the modifiers to your object worked? We're releasing v1.1.0 in the coming days/weeks which is completely refactored.

**Comment by vxlcoder** [comment]
since ver 1.1.0 requires 2.75+, should we close this?

**Comment by carter2422** [comment]
Yep. Just need to be sure we put in the checks to only allow enabling in 2.76+
