### ISSUE TITLE
MacOS RetopoFlow 3.2.8 - on undo retopo scales up

### ISSUE THREAD

**Issue by SurpriserTR** [CGCookie/retopoflow#1151]
During the retopolizing whenever I try to undo (ctrl+z) the models scales up.
Made some research and changed the 'z' relax with another key but still I have the same error
All the time I exit from retopoflow and re-open it which solves the problem but takes so much time
![image](https://user-images.githubusercontent.com/43583369/184880122-fb11946b-c7e5-4e02-a6f0-7761c2c19551.png)

**Comment by vxlcoder** [comment]
thanks for the report, @SurpriserTR, and nice model!

this issue has been fixed in the latest branch `v3.3.0`, but we are still making some significant changes, so we haven't released it yet.

I am working on a quick fix now for this exact problem.  we are planning to release this in the next few days.

if you want to try `v3.3.0`, you can get it from https://www.dropbox.com/s/e2n3ikarenznwtd/RetopoFlow_v3.3.0-alpha-GitHub.zip?dl=0. do note that this version is still a work in progress.

**Comment by SurpriserTR** [comment]
Wow thank you a lot for quick response .
I will try the v3.3 version but I’am not sure if its working well with MacOs.
Good luck .

Jon Denning ***@***.******@***.***>> şunları yazdı (16 Ağu 2022 15:45):



thanks for the report, @SurpriserTR<https://github.com/SurpriserTR>, and nice model!

this issue has been fixed in the latest branch v3.3.0, but we are still making some significant changes, so we haven't released it yet.

I am working on a quick fix now for this exact problem. we are planning to release this in the next few days.

if you want to try v3.3.0, you can get it from https://www.dropbox.com/s/e2n3ikarenznwtd/RetopoFlow_v3.3.0-alpha-GitHub.zip?dl=0. do note that this version is still a work in progress.

**Comment by vxlcoder** [comment]
As far as we can tell, it _should_ be working fine on MacOS, but please let us know if you do run into problems!

**Comment by jlampel** [comment]
We haven't seen this come up since the fix was included with 3.2.9. Please let us know if it happens again in the latest version.
