### ISSUE TITLE
3.8.9 update, error during installation

### ISSUE THREAD

**Issue by GMJ80** [CGCookie/retopoflow#1159]
[BUG] 2.8.9 update, error during installation

Retopoflow Version: 2.8.9

Blender Version/Hash: 3.2

Platform Version/Distribution: WIN10

I've recently bought Retopoflow and started using with a 3.2 version of Blender. I've bumped into a few issues during the first uses, like upscaling target meshes beyond others. It was very promising to see your note on the weekend thaht you've made an update of Retopoflow, which handles these issues. However, the install process was unsuccessfull, unfortunately. When first tried to do it through the addon's updating system, it brought up an error message about faulty scripts in the install files. Then I downloaded the .zip file from the Blender Market order page and after installation the addon disappeared from Blender's viewport. In the addon list I've found an error message, that there are missing script files in RTPF (screenshot is attached about it). Could you help how could I solve this issue, to start using the addon again? Thank you

**Comment by vxlcoder** [comment]
Hi @GMJ80.  I'm sorry to hear that you've had so many issues.  We'll work to get you up and going.

I did not see an attached screenshot, but some people have had some issues with the updater.  Not sure yet what the cause is, but we're still digging into that.

For now, a working workaround has been: uninstall RetopoFlow completely from Blender, restart Blender (completely close then reopen), install the latest version of RF (v3.2.9), and finally enable RF.

Let us know if you're still having problems.

**Comment by denschub** [comment]
@vxlcoder I have the impression that the .zip uploaded to BlenderMarket is wrong. Instead of having a top-level folder `RetopoFlow` inside the zip, the addon is inside a `RetopoFlow_v3.2.9-BlenderMarket/RetopoFlow/` subdirectory, which isn't valid and causes the update to fail.

I initially thought macOS played a trick on me, but it's not:

```plain
# unzip -l RetopoFlow_v3.2.9-BlenderMarket.zip
Archive:  RetopoFlow_v3.2.9-BlenderMarket.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  09-16-2022 11:11   RetopoFlow_v3.2.9-BlenderMarket/RetopoFlow/
       99  09-16-2022 11:11   RetopoFlow_v3.2.9-BlenderMarket/RetopoFlow/.cgcookie
    31448  09-16-2022 11:11   RetopoFlow_v3.2.9-BlenderMarket/RetopoFlow/__init__.py
...
```

**Comment by denschub** [comment]
Interestingly, the GitHub release is fine:

```plain
# unzip -l RetopoFlow_v3.2.9-GitHub.zip
Archive:  RetopoFlow_v3.2.9-GitHub.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  09-16-2022 01:53   RetopoFlow/
    31448  09-16-2022 01:55   RetopoFlow/__init__.py
```

so something went wrong preparing it for BlenderMarket? :)

**Comment by vxlcoder** [comment]
oh, interesting catch!  the makefile should create similar structured zips, so maybe the BM version was uploaded wrong?  @jlampel can you take a look at that?

**Comment by jlampel** [comment]
Thank you for reporting. That was my fault for zipping it up incorrectly after making a change (removing "alpha" from the version number) for the Blender Market upload. Apologies for that! I've fixed the BM download.

**Comment by GMJ80** [comment]
Thank you all, for your quick response and helpfull manner. I'm excited to check the update. Thank you for it, again.
