### ISSUE TITLE
[QUESTION] What do I need to do to UV unwrap the complete target mesh, which was made in X smmetry in Retopoflow (Blender unwraps only one side of the target mesh, without handling the mirrored side)

### ISSUE THREAD

**Issue by GMJ80** [CGCookie/retopoflow#1161]
[QUESTION] What do I need to do to UV unwrap the complete target mesh, which was made in X smmetry in Retopoflow (Blender unwraps only one side of the target mesh, without handling the mirrored side)

Retopoflow Version: 3.2.9

Blender Version/Hash: 3.2

Platform Version/Distribution: WIN10

It is my first target mesh I've created in Retopoflow, which I made with using X symmetry and now I'm trying UV unwrap it. I made the prep work, like closing all open loops within the mesh, marking the seam (for unwrapping) as a continuous loop. The seam is the central symmetry line in the front view and what I get in the UV editor is only one side of the target mesh, like it was not mirrored to create the complete mesh. It looks as if a mirroring function would not be applied and Blender sees only one side of the target mesh, which was mirrored to the X axis. When I check the mirror modifier of the target mesh, I can't set it to be applied, as it's disabled. I have attached a screenshot about the viewport, the UV editor and the mirror modifier parameters. Could you perhaps help what should I do to use the complete target mesh in the UV unwrapping? Is there perhaps any finalizing step when I close my Retopoflow editing, which should create the mirrorred mesh?

Thank you for your help

![kép](https://user-images.githubusercontent.com/113591169/192275969-2fd7ad0e-bbdf-48d9-9971-0aaaed122890.png)

**Comment by jlampel** [comment]
Hi, apologies for the late reply! This didn't look like a bug when I saw it, and I neglected to come back to it. RetopoFlow mirrors using Blender's mirror modifier. To unwrap the full mesh, apply the mirror modifier. I would generally recommend leaving the edit mode visualization off for modifiers (the left most icon that looks like an upside-down triangle) to avoid this type of confusion. It's greyed out because modifiers can only be applied in object mode. 

Hope that helps!
