### ISSUE TITLE
Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by funkcanna** [CGCookie/retopoflow#1197]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Crash When Using Knife**

{*Retopoflow crashes when I try to use the knife on an existing retopoflow mesh*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- Reopen a retopoflow mesh, try to use the knife

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.9
- CG Cookie built for Blender Market
- Blender: 2.93.3 master 2021-08-17
- Platform: Windows, 10, 10.0.22621, AMD64, Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 527.56, 4.50 NVIDIA
- Timestamp: 2023-03-13 06:53:08.000543
- Undo: insert, grab, select, select, select, select

Error Hash: 96cc5299d67f02b3d9cff2c8daf6509d

Trace:

- EXCEPTION (<class 'NameError'>): name 'clipboard' is not defined
-     <string>
- 000 0001:<module>() 
-     .../common\utils.py
- 001 0165:run_it() return exec(action, f_globals, nf_locals)
- 002 0170:run_it() raise e
-     .../common\ui_core.py
- 003 2068:_fire_event() cb(details)
- 004 2074:_fire_event() raise e
- 005 2105:dispatch_event() self._fire_event(event, ui_event)
-     .../common\ui_document.py
- 006 0555:mousedown_exit() under_mouseclick.dispatch_event('on_mouseclick')
-     .../common\fsm.py
- 007 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by funkcanna** [comment]
this seems to happen when there is no base mesh underneath the retopo'd mesh

**Comment by vxlcoder** [comment]
thank you for the report @funkcanna.

i'm not too sure what issue you were running into directly, though.  turns out, the details your pasted above are for an entirely different issue, which is now fixed in commit 9a56768.

I've tried replicating your particular issue, but i'm having trouble figuring out how to do that.

can you provide a few more details?  are you able to replicate this issue on the default cube, or does it only work on one particular .blend file?

**Comment by funkcanna** [comment]
It happens on all blend files. But only happens when the area of the new retopoflow mesh does NOT have a base mesh underneath.  So if I retopoflow the front of a tshirt, then go back to blender and hide the original tshirt, and show for example the collar of the tshirt and then go back to work on the retopod front of the tshirt, which now has no base mesh visible underneath and try to use the knife, this crash happens.

**Comment by vxlcoder** [comment]
@funkcanna, commit 0ef93c0 _should_ work around this issue.

a note: RF requires a source mesh (ex: the tshirt in your situation) in order to know where new geometry should be placed.  if you hide the underlying geometry, RF doesn't know where to place things.

in this case, we could fall back to using existing geometry to place new geometry, but that would require a bit more work.  the commit above prevents the crashing, but is not a perfect solution.

you can test it using this temp link: https://www.dropbox.com/s/bee8gmq16escltz/RetopoFlow_v3.3.1-alpha-GitHub.zip?dl=0

**Comment by jlampel** [comment]
This appears to be fixed on my end. Let us know if it happens again!
