### ISSUE TITLE
***[BUG]*** No Headings in the Options Menu

### ISSUE THREAD

**Issue by Pyrapon** [CGCookie/retopoflow#1198]
Version 3.2.9

The Options Menu located in the upper right-hand side of the viewport does not have any text where the headings for each section should be. The arrow to unfurl each section can be seem, and operates as expected, however, being new to RetopoFlow, it means I often am just going down the menu unforling sections until I find the Symmetry section.

**Comment by jlampel** [comment]
Hi there, can you try adjusting the UI scale to see if that has an effect? It's in the first panel and the first sub-panel:

![image](https://user-images.githubusercontent.com/12982300/225083500-bf5b6c8b-3603-4841-b369-d2be5dc53066.png)

We used to have an issue with disappearing text at some UI scales, and that's based on your Blender preferences, so my guess is that you have Blender set to a UI scale that we missed testing when that bug was resolved. 

Try changing it to 0.9, 1.1, 1.25, etc. Let me know if that does the trick!

**Comment by Pyrapon** [comment]
Hey Jonathan, that did indeed fix it. Thank you for getting back to me so
fast, it's much appreciated.

(Also, I went ahead and checked my Blender preferences under the Interface
section and I had my Resolution Scale set to 1.05, if that's helpful in any
way for you all down the road.)

Thanks again,
-James

**Comment by jlampel** [comment]
Great! Glad that did the trick. I'll close this out then and open https://github.com/CGCookie/retopoflow/issues/1135 back up with this info.
