### ISSUE TITLE
Strokes: Crossed quad sometimes?

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#1225]
Sometimes, Strokes can create crossed quads.

For example, in [The Complete Guide to Retopology with RetopoFlow 3](https://youtu.be/9OjS2rU-Jr0?t=1358), we get the following if stroking left-to-right, but not right-to-left.

![image](https://github.com/CGCookie/retopoflow/assets/3790699/373571df-2fb0-4c0e-bfa9-f5923626b418)

![image](https://github.com/CGCookie/retopoflow/assets/3790699/5aad0610-afdf-462f-8450-030656ee6956)

**Comment by jfranmatheu** [comment]
I'm investigating this issue, and while testing some things I made an example that triggers the issue drawing the stroke in both left-right and right-left


https://github.com/user-attachments/assets/13a0c05e-260e-4b01-8993-45928f9c7ffb

**Comment by jfranmatheu** [comment]
The cool thing is I managed to fix it for the known/reported case, but since no matter if it's left-right or right-left, it does the opposite effect in the other case, doing it bad no matter the direction heh. Do it looks like something more deeper I still have to analyze better.

https://github.com/user-attachments/assets/cb0aa647-fddd-4491-9817-1d24e2d0b50b

**Comment by jfranmatheu** [comment]
Fixed with https://github.com/CGCookie/retopoflow/commit/1dfd2f7c90341015c8d8012dc55c8ed02027d9b5

Video:

https://github.com/user-attachments/assets/7793c4f6-e25a-4fa3-a0ac-c25104f80685
