### ISSUE TITLE
"The quick entry button is missing in editing mode in version 3.64."

### ISSUE THREAD

**Issue by sangouzhi** [CGCookie/retopoflow#1269]
![Snipaste_2023-10-03_19-03-05](https://github.com/CGCookie/retopoflow/assets/114461992/b4316822-ed1f-4efa-b88e-cf840f63bbc3)

~"Also, I have a feature request. With the new 'select' command, it's faster to select points, lines, and faces. I noticed that you added the 'ctrl+x' shortcut for quick deletion, which is great. Can you add a similar shortcut for quick merging of points, lines, and faces? Additionally, when using the 'knife' tool, it currently requires a right-click to confirm. It would be better if it used the native left-click instead."~ (edit: moved to separate issues, #1275 and #1276)

**Comment by sangouzhi** [comment]
"I was mistaken. The native confirm button for Knife is actually the space bar. Perhaps it's due to habit, but it seems like the space bar is more convenient."

**Comment by vxlcoder** [comment]
thanks for the report, @sangouzhi.

I will address your first issue here, and i'll split the other items into separate issues to help us track everything.

the quick entry button does not show up when RF detects a potential issue.  for example, in the screenshot below RF found an auto save (backup) that maybe the artist should be working with instead of the current file.  you can click the buttons next to "See details on these warnings" to get more details.  Clearing out these warnings, and then the quick entry button should show again.

![image](https://github.com/CGCookie/retopoflow/assets/3790699/4f2bba99-a1f9-42e9-a79e-da276dff5679)

does this address your initial issue?

**Comment by sangouzhi** [comment]
> 感谢您的报告，@sangouzhi。
> 
> 我将在这里解决您的第一个问题，并将其他项目分成单独的问题，以帮助我们跟踪所有内容。
> 
> 当 RF 检测到潜在问题时，快速输入按钮不会显示。例如，在下面的屏幕截图中，RF 发现了艺术家可能应该使用的自动保存（备份），而不是当前文件。您可以单击“查看有关这些警告的详细信息”旁边的按钮以获取更多详细信息。清除这些警告，然后快速输入按钮应该再次显示。
> 
> ![图像](https://user-images.githubusercontent.com/3790699/278894160-4f2bba99-a1f9-42e9-a79e-da276dff5679.png)
> 
> 这能解决您最初的问题吗？

good ,it's  already fixed  thank u
