### ISSUE TITLE
[QUESTION] Number of verts/edges not showing after clicking Strokes

### ISSUE THREAD

**Issue by laptop-laptop** [CGCookie/retopoflow#1273]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.4.0

Blender Version/Hash: 3.6.2

Platform Version/Distribution: Windows 10

&nbsp;

**Issue:**

Unlike shown in some youtube videos, after pressing Strokes, the number of verts/edges are not shown in the green area.
Not sure if this is a bug or there is an option to enable it.

Also, is the number shown in the video the number of vertices or number of edges? Can I have both displayed?

https://imgur.com/IlEl9BM

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
this has been fixed in commit 981d31b.  the shown count was for number of selected edges as strokes works with edges, but i agree that it's a bit ambiguous.  improved count reporting.

![image](https://github.com/CGCookie/retopoflow/assets/3790699/9bd0be0f-b487-4f8b-bc23-b9f9db29d21f)

also added counts for span/loop

![image](https://github.com/CGCookie/retopoflow/assets/3790699/ae476ed8-20b3-4a3c-910b-f65b97f07011)

![image](https://github.com/CGCookie/retopoflow/assets/3790699/592a3b94-b41c-46e7-b0b9-28340cd7ddf0)

thanks for reporting the issue, @laptop-laptop!

happy retopo'ing!

**Comment by laptop-laptop** [comment]
Thanks @vxlcoder   How do I get the fix? Do I have to wait for the next official release?

**Comment by vxlcoder** [comment]
I will send a link later today, but I am also hoping to get an official release out soon.

**Comment by laptop-laptop** [comment]
Thank you

**Comment by vxlcoder** [comment]
here is a temp link to the latest version (as of now): https://www.dropbox.com/scl/fi/7itaxnh7dmn8op7wpsp5w/RetopoFlow_v3.4.2-beta-GitHub.zip?rlkey=ztrd3stsibrjbmjtk3w8g7w41&dl=0
