### ISSUE TITLE
Polypen not work correctly

### ISSUE THREAD

**Issue by renx0x0** [CGCookie/retopoflow#1310]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*3.4.3*}

Blender Version/Hash: {*4.0*}

Platform Version/Distribution: {Win*}

&nbsp;

**BUG:**

{*Polypen not work correctly*}

{*in one of the screenshots, the vertex is hidden, and it won't connect. *}

&nbsp;

**How to Reproduce:**

- {*when I work with polypen and the points that need to connect are next to each other all is well, but if for example I need to create a large polygon for example hammer, and connect the points that are behind the screen, then polypen stops working, ie it does not create a polypen if at least 1 point is outside the screen visibility, it stops working, in previous versions of this was not, is it fixable ?*}

{*attach any files needed to replicate the issue*}
![Снимок экрана 2024-03-22 195422](https://github.com/CGCookie/retopoflow/assets/140628679/02ac3c33-0869-4b59-9095-a1e32bd827d6)
![Снимок экрана 2024-03-22 195416](https://github.com/CGCookie/retopoflow/assets/140628679/84a1c909-1d61-489f-a476-84fe73ea1ea0)

**Comment by vxlcoder** [comment]
Thank you for the report, @renx0x0.

Some of the logic behind many RetopoFlow v3.x tools, including PolyPen, require knowing which geometry is nearest the mouse, sometimes looking at the nearest selected geometry.  When the geometry is outside the view, what is nearest to the cursor is not always what seems like is nearest.  And knowing how to tell them apart is difficult.  (This becomes even more unintuitive when the geometry is behind the view.)

In RF v4, we're changing the logic a bit to use world space for most decisions rather than screen space.  This handles more cases like this much better, but sometimes it can also produce unintuitive results.  Thankfully, the previzualizations give you a chance to see what's going to happen before you commit to making the change, and so you are able to make adjustments if it's not quite right.  (so taking an approach where it's right ~90% of the time but can correct for that ~10% instead of taking an approach where it's ~98% correct but doesn't do anything when all the conditions aren't perfect)

I think this particular case should be an easy fix.  at this moment, i'm not sure when I will be getting to it though.  (really trying to push out RF v4!)

**Comment by renx0x0** [comment]
Thanks so much for the reply! Looking forward to the new version of your wonderful addon! Good luck to you!
