### ISSUE TITLE
4.1, Cant load addon

### ISSUE THREAD

**Issue by The-Maize** [CGCookie/retopoflow#1315]
![image](https://github.com/CGCookie/retopoflow/assets/70098123/8548e191-49e6-4552-832a-83844e1ebab6)

Retopoflow Version: {*add here*}

Blender Version/Hash: 4.1
cant load the addon in 4.1

Simple to reproduction, just install as normal addon then try to enable.

**Comment by vxlcoder** [comment]
@The-Maize, can you provide a bit more information so that we can help figure it out?

which version of RetopoFlow are you trying to use?

which version of blender?

has RetopoFlow worked before, and now it does not, or is this the first time you installed it?

did you get RetopoFlow from the blender Market, GitHub, or somewhere else? if GitHub, where did you download it? (sometimes GitHub does not package RF correctly, so that can cause problems)

thanks!

**Comment by The-Maize** [comment]
sorry I meant to add the version of retopoflow into the issue, just missed it for some reason. 
I'm using blender 4.1
retopoflow version 3.4.3
This is the first time im using retopoflow, i just purchased a course pack but I noticed retopoflow was available to learn and there was a link to the GitHub for educational purposes so I'm using that version while I learn and see if the tool is something I can replace topogun with. I just got the video series for retopoflow added in my account so I'm keen to see how it goes.

**Comment by The-Maize** [comment]
Ahhhh i see what's I did wrong. I've grabbed the wrong file, and it's interesting that the other one still installs and detects that it is a plugin and shows up. Okay mark this as a pebcak error XD. 

For anyone else that had this - get the one marked -GitHub in the releases page rather than the other zip files.

**Comment by vxlcoder** [comment]
lol.

glad it was an easy fix. let us know if you have any other issues or questions!
