### ISSUE TITLE
[BUG] Mesh viewing errors after saving .blend and reloading

### ISSUE THREAD

**Issue by BlankMauser** [CGCookie/retopoflow#1316]
Retopoflow Version: 3.3.0

Blender Version/Hash: 3.3.6

**Issue:**

After saving my .blend file and hitting start retopoflow on my target mesh, my source mesh has errors:

![image](https://github.com/CGCookie/retopoflow/assets/17075881/23949c99-3f06-44de-98dd-c8f32e2a8fd8)

This issue did not happen before I saved the .blend file and reloaded. This viewing error also only occurs when starting retopoflow.

The arms were moved using the rig in pose mode, however this issue was not present before I saved and reloaded. I have attached the blend file here: https://drive.google.com/file/d/1tjxdlQo_04XBdB_rTA67R5JfEP6Zc6dc/view?usp=sharing

**Comment by vxlcoder** [comment]
Thanks for the report, @BlankMauser.

It looks like the armature on your source mesh is causing this issue.  Normally, the source mesh is in a static pose during the retopo session, because the target mesh isn't weighted to that armature, and reposing the source mesh would change the position of the surface.  So, RF assumes that your meshes do not have an armatures/rigs.  (there is a small warning about it in the menu)

![image](https://github.com/CGCookie/retopoflow/assets/3790699/5115e9f0-6793-4ce3-808b-3dd088e2d1fc)

A workaround for now is to apply the armature to your source meshes.  This is not ideal, but it would get you up and retopo'ing quickly.  (Alternatively, duplicate the mesh, apply the armature to the duplicated mesh, hide original mesh.  this would allow you to keep the original in case you want to repose it, but it would allow RF to work based on its simple assumptions)

Longer term, I'm not sure if there is a good way to fix this in RetopoFlow without some serious work due to these fundamental assumptions in RF 3.  RF 4 is currently under development, which does not have this issue, so I will close this issue for now.  Keep an eye out for RF 4, though!

Please let us know if you have any other questions about this issue or if you have other problems!

Happy retopo'ing!
