### ISSUE TITLE
Eyedropper: first time run takes a long time

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#141]
When starting the eye dropper for the first time it takes significantly longer than subsequent loads. This can be seen here: https://www.youtube.com/watch?v=PQq2-M5IE3w

Is this due to creating the BVH tree the first time around, similar to Contours and Polystrips?

**Comment by patmo141** [comment]
this Op doesn't create a BVH because it uses the "Scene.ray_cast" method.  Presumably, Scene.ray_cast has to do a bunch of updating on all the objects to ray cast all of them.  That would be my guess as to why this operator starts slowly.  Then Blender is caching things on it's own, so it's faster at subsequent calls.  This op however is doing no "manual labor" in terms of BVH or ray casting so there really isn't anything to optimize.

**Comment by carter2422** [comment]
Okay cool. No worries then.
