### ISSUE TITLE
Visualization occlusion is not clipping enough on thin meshes

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#148]
For example: http://cl.ly/dR9B

There's two things going on:
1. The thin areas do not get occluded at all
2. The thicker areas only occlude the face fills, not the edges and verts.

**Comment by carter2422** [comment]
Test model here: https://www.dropbox.com/s/abeimduij63xpyv/mesh-thickness.blend?dl=0

**Comment by vxlcoder** [comment]
unfortunately, this is an artifact of how we do 3d rendering.  we fake "draw on top" by manipulating the depth range, which causes problems when working on small surfaces.  one "fix" is to scale the model up before working on it.  alternatively, we expose the depth range values to allow the user to change.  the latter is a terrible idea, because artists should not need to know about this.

overall, this is a hard / impossible problem to solve with the way we are drawing it.  maybe we can work with blender devs in getting better opengl drawing support in bpy?

**Comment by carter2422** [comment]
Working to get better OpenGL drawing in sounds like a better solution.

**Comment by vxlcoder** [comment]
@carter2422 can we close this issue?  besides, it's more an enhancement than a bug, and it will be one that we cannot solve entirely, only continue to improve upon.  when blender 2.8 comes out, we might have better control over rendering, but only time will tell.

**Comment by carter2422** [comment]
Sounds good @vxlcoder. Closed.
