### ISSUE TITLE
Add-on Update Module

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#216]
The goal of the add-on updater is to enable RetopoFlow users to update their install automatically with a single click. 
# Features

A few key features are to be included:
- [x] Notification of new version available
- [x] Ability to single-click update to download and install new version
- [ ] Optional authentication against Blender Market with license key

The development of this is being handled in three stages:
## Stage 01- Initial Integration

Auto updating feature built into RetopoFlow, enabling auto download/update from specified Github repository.
## Stage 02 - Python Package

Standalone updater as a Python package, enabling other developers to easily integrate the functionality into their add-ons and and repositories.
## Stage 03 - License Key Integration

Integration with licensing software, enabling customers of specific platforms, such as the Blender Market, to access new versions with a valid license key.

**Comment by TheDuckCow** [comment]
@carter2422 perfect, appreciated! I'll have some more time to crack at this over the weekend.

**Comment by TheDuckCow** [comment]
@carter2422 first push is up, you'll notice there are two files added to the repository:

*addon_updater.py:* This is our main updater class module that already has many of the working pieces specific to git repo's, such as being able to pull the most recent tag name and convert it into a tuple to compare blender addon version numbers to (currently no bpy code though, and I think as much as possible it should be aimed to stay that way)

*updater-test-bench.py:* This is a test file you can run from a command line to test what I've done more or less so far. The code contained in this file would more or less be the interface that a developer would see and use.

One thing I am starting to flush out more (and certainly can take input on) is all of the sets of options for how to configure the updater. The first stage is of course making it work with retopoflow which I will continue to do, but I am being mindful of the later stages and being flexible with other repositories. For instance: Retopoflow only uses tags, not releases, for version updates. Other repositories might want to use releases and not use tags for example. Hence the somewhat placeholder option "use_releases=False", there are many more things like this that can be added. I have written some notes of this in the testbench file.

**Comment by carter2422** [comment]
Great @TheDuckCow! I haven't had a chance to really look at this yet but thanks for the update. Sounds like great progress. 

>Retopoflow only uses tags, not releases, for version updates. Other repositories might want to use releases and not use tags for example. Hence the somewhat placeholder option "use_releases=False", there are many more things like this that can be added. I have written some notes of this in the testbench file.

Are releases merely annotated tags? Can you have a release without a tag?

**Comment by TheDuckCow** [comment]
Hey @carter2422 , sorry thought I already responded. Essentially yes, annotated tags; you can't have a  release without a tag to my knowledge. Main use case would be for people to exclude betas or WIP from a release page. For example, these two repositories:

Releases:
[Retopoflow, none](https://api.github.com/repos/cgcookie/retopoflow/releases)
[MCprep, several](https://api.github.com/repos/theduckcow/MCprep/releases)

Tags:
[Retopoflow, several](https://api.github.com/repos/cgcookie/retopoflow/tags)
[MCprep, the same as releases](https://api.github.com/repos/theduckcow/MCprep/tags)

Note the information returned is a slightly different format though. Individual release can even include custom / extra upload data, such as how I use the MCprep addon releases to include rigs and textures in the release file I want to be used, without actually including those in the git repo itself (I just upload the zip with the assets added to that specific release). So in the case of MCprep, I would want the updater to pull its updates from the so called "browser_download_url" instead of source tarball. 

So in essence, even just on github different users might want to use different setups. The way Retopoflow I think is a good default, but having other options for what and how to pull info would be useful (if to nobody else, at least to me!)

**Comment by carter2422** [comment]
Good to know @TheDuckCow and nice foresight.

**Comment by TheDuckCow** [comment]
@carter2422 sorry I know a "couple days" turned into a week+ for having part one (and 2) mostly finished. In a time crunch with other work, but I'm at the stage where I'm integrating it with Retopoflow's UI and calling the functions from the UI. I'll work to get the bare bones thing out as soon as I can dedicate the time (read: likely weekend) and worry about polishing all the other parameters and options after you can give that a lookover.

**Comment by carter2422** [comment]
Sounds good @TheDuckCow, looking forward to it!

**Comment by TheDuckCow** [comment]
See the above code update, you should be able to download the repository as-is and install. The version is a stripped down version of the addon which just registers the addon updater code. Once enabled (should say v1.1.9), search for the operator "Update retopoflow addon", check for update and then choose update. 

See video for more details
[https://youtu.be/N4QJ3uctAus](https://youtu.be/N4QJ3uctAus)

Note I would not say part 1/2 are both done just yet, but it is very close needing some cleanup. Looking to hear any feedback or comments!

**Comment by vxlcoder** [comment]
@TheDuckCow, this looks super convenient!

maybe you have fixed this already since you made the video, but `__init__.py:103` and `__init__.py:135` is misspelled; should be `register_updater()`.

**Comment by TheDuckCow** [comment]
Ah, thanks @vxlcoder for the notice, fixed in my local copy so next version will actually spell updater correctly :)

**Comment by vxlcoder** [comment]
great work on this :)

**Comment by carter2422** [comment]
That's looking great @TheDuckCow! It'll be a few days (at least) before I can dive in and really try this out so go ahead and start polishing things up as you see fit. 

I really appreciate that you did it in such a way that the actual add-on integration for the UI and such is very flexible. This is something that I plan to experiment with a good bit to find what works well. 

Great work!

**Comment by TheDuckCow** [comment]
Hey @carter2422 did you get a chance to look at the code at all? And responses/changes in direction recommended?

**Comment by carter2422** [comment]
Unfortunately I haven't been able to check it out yet @TheDuckCow :( Hoping for next week.

**Comment by carter2422** [comment]
@vxlcoder if you get bored feel free to chime in here as well :)

**Comment by TheDuckCow** [comment]
No problem - I know what my next steps are anyways so I will continue forging ahead with that as I get time.

**Comment by carter2422** [comment]
Great, thanks!

**Comment by carter2422** [comment]
@TheDuckCow and I just had a call on this. We're a bit behind but aiming to complete this by end of June for v1.3.0, with the goal then to showcase it at SIGGRAPH!

Here are the notes from our call:

- First two phases have sort of been squashed into one
- About ready to push code to https://github.com/CGCookie/blender-addon-updater
- Main question is how to check for updates without interrupting the user
 - This must happen asynchronously 
- @TheDuckCow is going to handle the RetopoFlow integration
- Goal is to finish integration, minus authentication portion, by end of June
- @TheDuckCow will aim to present the package at the Blender Birds of a Feather at SIGGRAPH

**Comment by TheDuckCow** [comment]
Hey, still hoping to post some level of an update tonight thought getting slightly late. Just wanted to say got a little hung up on retopoflow crashing on reloading; the previous issue I fixed by commenting out one line in register, then it started happening again when running the ui panel code (where one of the notifications for updating may appear). [Issue reported here](https://github.com/CGCookie/retopoflow/issues/249#issuecomment-228655873)

**Comment by TheDuckCow** [comment]
Alright, and the update. As per usual, [here's a video demo](https://youtu.be/ExOLQ-dYtGU), and there below [here is the tag release of this code](https://github.com/TeamDeverse/retopoflow/releases/tag/v1.1.9) on the Deverse branch (which has the fix for the crashing/reloading issue)

Let me know what you think based on the video soon as you can, so I can get cracking on any changes or direction recommendations! Once I have background processing/threading done, will update again as well as finally push to that other repository for a first draft at the public module; again, it's the same code I just may need to clean up the example operator file to remove "retopoflow" etc.

**Comment by carter2422** [comment]
This is looking great @TheDuckCow! I just have one initial suggestion and a comment.

Suggestion: add ability to *Cancel* after *Check Now*

I also noticed that after updating to `1.1.9` the update button still said [*Update now to (1.1.9)*](https://youtu.be/ExOLQ-dYtGU?t=4m22s)

I assume background processing is the main open task?

**Comment by TheDuckCow** [comment]
Thanks @carter2422 
Re: cancel, sure thing I'll have it do that instead of show processing (once the async part is implemented)
Good call about the 1.1.9 post update. At that stage, I would presume a grayed out button saying up to date would be sufficient. On the right side, the first button is aiming to allow you to reinstall the current version or any old version as desired (obviously, reverting to a version to before the implementation of the updater code means you can't revert via the UI)

Background is the main task, but I was able to find working examples and have confidence in finishing the implementation. The other feature I'm hoping to finish is along with and related to being able target which version to install/revert to, also use a UI list to display any version notes/change log if found (as previously discussed).

**Comment by TheDuckCow** [comment]
Time for the big update! Test out [the RetopoFlow addon with updating capabilities here](https://github.com/TeamDeverse/retopoflow). Admittedly, it's probably still a beta feature because we need to do some robust testing (cross platform etc), but it would be safe for you to play with at this point. Again, currently hosted on the deverse page. I'm hoping to finish this to be full polished asap to merge into retopoflow master. 

@carter2422 some notes:
- Things to try and test:
  - Check for update button in user preferences (does it move to "processing.." and then whether or not there is an update ready?"
  - Check if it auto-updates in background, first in user preferences enable auto-check, then without pressing check for update, go over and simply open the retopoflow panel; if it works (and an update is ready), a popup should appear (too invasive?) as well as a UI update box in the panel at the bottom.
  - Checking for updates should always start a background thread and not block blender's interface, however running install update does block it. This is somewhat by design, but I could see the argument for wanting to make this a background process too. 
  - Set the user preferences to auto-check, set the interval to e.g. 3 minutes, press update once, save preferences, then 1) open blender in < 3 minutes, go to retopoflow panel, should be no background thread spawned (ie no update notice), then 2) close and open blender in > 3 minutes, go to retopoflow panel and see there shoudl be a popup indicating update ready. 
  - After pressing check for update (which inherently grabs all version numbers), try installing another version using the popup and dropdown
  - Press the install update (after checking by button or letting it check in background), see if it runs and after finishes it provides a popup saying it was successful (note: still says "*redo unsupported*", that's blender auto adding that in and I'm seeing if there is a way around it still)
  - After having done an update, see if you can revert the code using the restore backup button
- Reverting has been added as a feature, but obviously it's possible to revert back to a version to before when the updater code was installed (or was still WIP). 
- The way I personally test is actually have the most up to date code, but then alter the version number in `__init__.py` to be something other than the real version, so check for update thinks there is an update.
- It's currently pointed towards [https://github.com/TeamDeverse/retopoflow/releases](url) for the live integrated version, and will pull tags/releases from there.
- I am ready to update the [repository here](https://github.com/CGCookie/blender-addon-updater), but **I am not assigned to a team which has access to change this repository.** On the side, I will work to improve documentation, as there is a lot to explain since integrating with the user interface (esp. with background processing) can be rather complicated. I will also want to set this repository up to have at least one tag/release so that the included demo works out of the box.
  - Once I have access, I will push my staged git commit and then mark the "module checkpoint" as complete, since it is working at this moment in time.

I can work to demo a video of the most current code, may not be till tomorrow.

**Comment by carter2422** [comment]
@TheDuckCow I'm running into a problem with the add-on thinking it's always up to date, even when v1.1.11 is installed, or even when I manually edit `__init__.py` to force it into being an older version. It seems to be stuck thinking it's up to date ever since the first time I updated (at which time it worked perfectly). 

What determines wether or not the `up to date` flag is changed?

**Comment by TheDuckCow** [comment]
Does it still think it's update to date after a blender restart? If not, it's a known state issue where I need to add an addition stored variable to json file which stores some basic info in the back end (essentially I'm avoiding doing another internet call check, and so it should cache whether it is updated or if a previous version was intentionally installed). However, if it persists after a blender restart then I may need to look a little further. Do you have auto-check (ie interval) enabled? Consider setting the time step to e.g. 2 minutes to debug situations before and after an interval has passed.

I'm also working with another developer who is attempting to integrate the updater code in a WIP addon, and have found a couple things that could be better done to accommodate other addon setups. I'll continue to make those changes. Mostly minor, but also helps to clarify the steps one needs to go through to make this integration. I am still working on the associated documentation with respects to this.

**Comment by carter2422** [comment]
> However, if it persists after a blender restart then I may need to look a little further. Do you have auto-check (ie interval) enabled? Consider setting the time step to e.g. 2 minutes to debug situations before and after an interval has passed.

It persists after a restart (and even a re-install). Auto check was originally disabled but then I tested it with a 1 minute schedule and it still claimed to be up to date.

**Comment by carter2422** [comment]
I've gone ahead and logged an issue here: https://github.com/CGCookie/blender-addon-updater/issues/3

**Comment by TheDuckCow** [comment]
Interesting. And this was using the release download of v11 or v12? Windows/mac/linux? (in case it's somehow because it can't modify the json file or something strange like that)

**Comment by carter2422** [comment]
This has been merged in! Any further to-dos/bugs can be logged as a new issue.
