### ISSUE TITLE
Source/Target object handler causes crash when disabling/re-enabling add-on

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#249]
Per @TheDuckCow on Slack:

> Hey @carter2422, so you know how once upon a time we were talking about an issue where (on macs only?) blender would crash when disabling and then re-enablign retopoflow? I think I back-traced the issue.
Without doing much checking beyond checking/unchecking, I found the crash no longer happens if I just comment out this line in register, ie making it not add this handler:
bpy.app.handlers.scene_update_post.append(check_source_target_objects)

> Then exploring a little further, I first commented out all lines of that function, added a print statement to the hanlder and line-by-line started started uncommenting the code

> first thing I noticed is that, whether intended or not, the function handler is being run essentially all the time (continuous print statements going off). Perhaps I misunderstand this specific handler, but I thought it’s supposed to only trigger after running an operator or making any change of a blender datablock.

> Next I found that, with everything else commented out including and past this following line, no crash occurs on re-enable:
`if settings.source_object not in bpy.context.scene.objects:`

> But if this line is not commented out (and I add e.g. an intended print statement after to not get a syntax error with the if statement), then the crash does occur when reloading the add-on and ultimately, I now find that the crash is just because of trying to access: settings.source_object

> **in reference to `def check_source_target_objects`: The reload crash is happening when trying to access this attribute after the addon has been disabled and re-enabled. I haven’t looked further into it yet, but I imagine it has to do with the way the attribute/settings variable is cleared on disable and attempted to be reloaded on enable.

**Comment by TheDuckCow** [comment]
Hey, I found another place where this comes up. I recorded a video which is better at explaining than I could do in text, take a look at this here when you can: [unlisted youtube video](https://youtu.be/itJZtAalFro)

But, for giving a stab at the specific and then the larger issue:
- In the common_utilities module, there was a line of code at the root/global level: `get_settings.cached_settings = None` ; this works fine when blender is opened for the first time as all the modules are run, including code at the global level (ie not contained in a class or definition). However, when the addon is disabled and re-enabled, even though the addon was disabled *the module still exists in memory.* Which means, any lines of code defined at the global scope are not rerun.
- In this specific example, the issue was that `get_settings()` would crash blender (called from the UI toolbar panel to get settings) because the variable `get_settings.cached_settings` was not reset to `None` so it expected settings to be there (but in some way the cache is not present or otherwise not formatted in a way it should be after having been disabled/enabled)
- The short solution: move the `get_settings.cached_settings = None` of code from common_utilities.py to the register function of the in the `__ init__.py` file: first `from .lib import common_utilities` at global scope and then `common_utilities.get_settings.cached_settings = None` inside the `__init__` register function; as far as I know, it's not needed to place anything in the unregister definition. 
- The long term solution: move ALL global-scope level (zero indentation) code into def register() functions for each of those files, or otherwise create a system where the code is ensured to be run not just the first time blender is opened, but every time the adodn is enabled so that it's a consistent starting state. 

Let me know if that seems clear enough or not, happy to go through it further.

**Comment by carter2422** [comment]
Ah very nice find @TheDuckCow! Would you want to go ahead and submit a pull request with those changes?

**Comment by carter2422** [comment]
Thanks again for tracking this down @TheDuckCow.
