### ISSUE TITLE
Show/Hide Visibility (extension)

### ISSUE THREAD

**Issue by animatoring** [CGCookie/retopoflow#335]
Could a show/hide option be added for the polypen tool? It could help a lot for points that are in tight locations. Thanks!

**Comment by vxlcoder** [comment]
"show/hide" similar to "reveal/hide selection" of edit mode?

**Comment by animatoring** [comment]
yes please if possible, thanks for all of the hard work so far!

**Comment by carter2422** [comment]
I've found myself wanting a hide/show feature as well at times, it's certainly useful. My only hesitation is that we'd merely be replicating another Blender feature. 

If we can find a nice way to do it in a way that extends Blender regular hide/show tools, rather than merely recreating it, then I'm open minded! 

This could be a nice 2.1 feature.

**Comment by animatoring** [comment]
Have you been able to use Blender's show/hide within Retopoflow? I haven't had much luck using it within the polypen tool.

**Comment by carter2422** [comment]
> Have you been able to use Blender's show/hide within Retopoflow? I haven't had much luck using it within the polypen tool.

We don't currently support hide/show, since we're drawing all geometry in our own RetopoFlow style, which is what enables us to ensure the PolyPen geometry draws on top of the surface.
