### ISSUE TITLE
Visibility issue

### ISSUE THREAD

**Issue by 1vanK** [CGCookie/retopoflow#336]
On the video I noticed that low-poly geometry is visible over HiPoly. May be it not works with latest version of blender? I enable X-Rays for it, but when I press "Tweak" button, target object is complete invisible

**Comment by animatoring** [comment]
Hi 1vanK, is the visibility of your high poly object on? I know it seems simple but if it is set to off is won't show through the tweak mode. I've been able to use tweak mode with the high poly visible on other objects in Blender 2.78.

**Comment by 1vanK** [comment]
Video: http://dropmefiles.com/VSpmW
What am I doing wrong?

**Comment by animatoring** [comment]
I think you had the cube selected when you when into tweak mode instead of cube_contours. Try switching cube_contours to the active object then going into tweak mode.

I tried it out like your video and got these results when I tested it:
![demo2](https://cloud.githubusercontent.com/assets/25253627/23517114/649d9552-ff3d-11e6-9a81-2d43e5096eff.PNG)
![demo](https://cloud.githubusercontent.com/assets/25253627/23517115/66d1baf6-ff3d-11e6-8b47-e60760442e58.PNG)

**Comment by 1vanK** [comment]
It is impossible to use tweak when source model is selected

![3](https://cloud.githubusercontent.com/assets/13021826/23517958/f28610de-ff82-11e6-9fb9-0a0a31320f78.png)

**Comment by animatoring** [comment]
When you go to object mode do you have the source as cube (high poly) and the target object as cube_contours (low poly)? I usually have that error when cube_contours (low poly) is set to the source.

![demo3](https://cloud.githubusercontent.com/assets/25253627/23518560/d5598b8a-ff41-11e6-9dff-5c633e31f786.PNG)

**Comment by animatoring** [comment]
If cube_contours is set as the source you get that error:

![demo4](https://cloud.githubusercontent.com/assets/25253627/23518773/97c0da34-ff42-11e6-9454-0770e39a057f.PNG)

**Comment by 1vanK** [comment]
I think some problem with manual drawing geometry. Real geometry is hided in tweak_modal.py
```
def start(self, context):
        ...
         # Hide any existing geometry
        bpy.ops.mesh.hide(unselected=True)
        bpy.ops.mesh.hide(unselected=False)
```
but after hiding overlay not drawn

**Comment by 1vanK** [comment]
Magik is Wrong!

I comment lines:
```
        // MAGIC!
        #gl_FragDepth = gl_FragCoord.z - 0.001*(2.0-d)/(l*l)*vDotOffset - clip*vOffset;
```
and at least see something

![3](https://cloud.githubusercontent.com/assets/13021826/23577293/689749ba-00cc-11e7-8812-2cb434a86c79.png)

**Comment by 1vanK** [comment]
ok, replacing (in both places)
```
varying vec4 vPosition;
varying vec3 vNormal;
varying float vOffset;
varying float vDotOffset;
```
to
```
varying highp vec4 vPosition;
varying highp vec3 vNormal;
varying highp float vOffset;
varying highp float vDotOffset;
```
solwed its problem on my videocard

**Comment by 1vanK** [comment]
Some problem with:
```
        // MAGIC!
        gl_FragDepth = gl_FragCoord.z - 0.001*(2.0-d)/(l*l)*vDotOffset - clip*vOffset;
```

when I comment in all works

**Comment by vxlcoder** [comment]
@1vanK and @animatoring: thanks for the report and in trying to debug.

rendering has always been problematic, especially when model scales and clip start/end values can all be wildly different.

which version of retopoflow are you using?

**Comment by 1vanK** [comment]
last version from repo

**Comment by 1vanK** [comment]
I'm not sure, but may be glPolygonOffset() will work better than depthRange

**Comment by vxlcoder** [comment]
Thanks for the suggestion, @1vanK!

Sadly, we've tried many approaches, glPolygonOffset included.  Each had their own advantages, but all fall short of solving the actual problem: getting the target geometry to render correctly over the source geometry that it covers but not other parts, such as wrapping around the backside of the object or extruded parts.  The GLSL hack is there as an attempt to give us fine-grained control, but then the solutions requires fine tweaking.  The glDepthRange and glPolygonOffset hacks also requires tweaking to get just right.

In the end, any hack that requires tweaking will always works well for certain scales, types of surfaces, and near/far planes, but then fail miserably with others.

Note: this is not a rant or an attempt to shoot down ideas.  On the contrary, _please_ keep them coming!  We need all the help we can get :)

Perhaps we should revisit old attempts or even change our approach altogether, like taking a more systematic and robust approach instead of layering on the brittle hacks.  Honestly, being a computer graphics prof, hack fixes never sit right with me...  maybe there is an academic paper that can come from this...

**Comment by 1vanK** [comment]
Is there a way to receive texture with viewport depth and sent to "draw target" shader?

**Comment by 1vanK** [comment]
https://github.com/dfelinto/blender/blob/master/source/blender/gpu/shaders/gpu_shader_fx_dof_frag.glsl

As far as I understand, exists a way to send depth of rendered viewport to "draw target" shader and compare "viewport depth" and "target depth" there

**Comment by vxlcoder** [comment]
thanks for the link!  few things:

- blender's bgl (and internally) is still using opengl 1 and some 2.x.  blender 2.8 is bumping that to opengl 3.  until then, a lot of useful opengl functionality is not exposed to python.  see https://wiki.blender.org/index.php/Dev:2.8/Source/OpenGL

- typically, i would render to a frame buffer, and then do post-processing (like the shader code you linked).  unfortunately, that isn't exposed in BGL, and currently there isn't a good solution AFAIK.

- for curved geometry, the highly tessellated source mesh can actually stick through the simpler, retopologized target mesh. Handling this would (likely?) require tessellating and then "shrink wrapping" the target mesh.

- depth is stored non-linearly (for a variety of really good reasons).  this means that sometimes the target geometry renders on top of target when the object is far from the viewer, but starts to disappear as you get closer.  scaling objects also affects this.

We're hoping to make due with what we have and wait out most of the issues until we have the newer opengl architecture to work with, because it will make solving these problems easier.  However, even with access to 3.x features, we will still have problems.  (hence the researching now)

**Comment by 1vanK** [comment]
> depth is stored non-linearly

depth texture uses to get real world coords of fragments and comparison real distances. If difference is small, then draw target geometry (it does not matter is target geometry in front or behind source geometry)

**Comment by vxlcoder** [comment]
correct.  but how much is "small"?

**Comment by 1vanK** [comment]
we can allow users to set this value :)

**Comment by carter2422** [comment]
Thanks for the input and help @1vanK! It's very much appreciated, particularly for tough visibility issues like this one. 

> we can allow users to set this value :)

I don't think having a option for something like this is a good solution. Good mesh visibility is something that should *just work*, particularly from a user's perspective. The user shouldn't have to fiddle with depth settings just to see what they're doing. 

My hope is that we can continue to improve the drawing such that it supports a wider range of scales, but that's proving difficult. 

Adding a user option is a simple solution, but if we keep adding options for tough corner cases like this then before long we have dozens of options and a whole new set of problems (over abundance and complication).

**Comment by carter2422** [comment]
We are solving this in v2.0! Thanks to some architectural changes this should become an issue of the past. 

I'm closing this since it'll no longer apply.
