### ISSUE TITLE
Polypen breaks display and goes black

### ISSUE THREAD

**Issue by r00tdown** [CGCookie/retopoflow#354]
Hi after using polypen for 5 mins my screen goes black like this in blender...

![a](https://user-images.githubusercontent.com/30971180/29246640-603d24a4-802b-11e7-96ae-5eb9ca3a9ca2.jpg)

**Comment by vxlcoder** [comment]
Thank you for the report, @r00tdown.

Does Polypen report any errors to you right before this happens?  Typically, this issue will show when a problem happens under the hood that wasn't caught.  If nothing shows in Blender, can you try running Blender from the terminal / command prompt, because errors will be reported there.

Let us know what is reported, and we can debug the issue.  Thanks, again!

**Comment by carter2422** [comment]
@r00tdown were you able to check and see if there were any errors reported? 

We're working on v2.0 right now, which is a complete rewrite, so unless there's a specific error given we'll close this and consider it resolved in 2.0.

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!
