### ISSUE TITLE
Polystrips: adjusting segments resets handle scale

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#380]
If you scale a handle on a strip and then adjust the segments the scale resets.

**Comment by vxlcoder** [comment]
Unfortunately, this is a limitation that might have to persist for a while.
The segment count adjustment reconstructs the strip, rather than adjusting like manipulating the handles does, because the topology actually changes (not just geometry).
A proper fix would require rewriting the segment adjustment code, which would involve a considerable amount of work.

Can this fix be delayed for now?

**Comment by carter2422** [comment]
Unfortunately this is a pretty bad shortfall, as the scale also resets at every transform. Mostly yielding the scale useable, if anything because of managing expectations from users.

If we're not able to solve it for beta then we can simply leave it out of the documentation for now.

**Comment by vxlcoder** [comment]
fixed!
