### ISSUE TITLE
Loops: Unhandled exception caught

### ISSUE THREAD

**Issue by TvoyBatek** [CGCookie/retopoflow#383]
If I try select this  edges by "Loops" tools

![photo_2017-08-12_20-56-12](https://user-images.githubusercontent.com/8208165/33419567-701dbe62-d5c4-11e7-95f1-ddd8535d4199.jpg)

I get an error
![blender_2017-11-30_11-39-30](https://user-images.githubusercontent.com/8208165/33419629-aa34e6fc-d5c4-11e7-8bbc-bac058389220.png)

Attached file with error. All retopology I did in Retopoflow.
[Test_01.zip](https://github.com/CGCookie/retopoflow/files/1516923/Test_01.zip)

**Comment by vxlcoder** [comment]
will take a look, @TvoyBatek.  Thanks!

**Comment by vxlcoder** [comment]
@TvoyBatek, the above commit does not yet fix the problem, but at least it doesn't report an error.

The issue was that one of the face loops crosses over itself, and therefore Loops would break whenever your mouse hovered near that loop.  I'll continue to work on it, but the commit above is moving in the appropriate direction.

Thanks for the report!

**Comment by TvoyBatek** [comment]
@vxlcoder Thank you!

**Comment by vxlcoder** [comment]
still needs work (sliding is based on horizontal change of mouse, and may be flipped--not intuitive), but i believe the issue of crashing should be fixed
