### ISSUE TITLE
Wm.py error in installation

### ISSUE THREAD

**Issue by nathanmiguel123** [CGCookie/retopoflow#445]
Before version 1.3.2 worked without any problem, but when I clicked on remove to install v2 the blender no longer wants to accept the installation of the plugin, both in v1.3.2 in both v2. The file says that it is wm.py at line 143 and 2045 in the blender installation folder.

**Comment by vxlcoder** [comment]
Thanks for the report, @nathanmiguel123.  I'm a little confused about what the problem is exactly.

Are you having trouble removing/uninstalling the previous version of RetopoFlow?

You should only need to upgrade the version using RF's add-on updater.

If possible, can you post a screenshot of the issue you're having?  Thanks!

**Comment by nathanmiguel123** [comment]
The update method only works to install version 1.3.2 or earlier, and to remove I opened the habe of the addon and click on the remove button

**Comment by nathanmiguel123** [comment]
![sem titulo](https://user-images.githubusercontent.com/29849613/38156522-e7a0d1ba-3454-11e8-929f-a73e70ef2d4b.png)

**Comment by vxlcoder** [comment]
@nathanmiguel123, can you try manually deleting the RetopoFlow folder from the add-ons folder?

**Comment by nathanmiguel123** [comment]
deletes the folder and the message disappeared, but now when I add the .zip addon the plugin folder goes to but does not appear to be active

**Comment by nathanmiguel123** [comment]
now you can rest easy, it was because the name had trace and space I just solved, thank you for the help
