### ISSUE TITLE
Close Tool Shelf and Properties Panel with "Maximize Area" click

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#450]

**Comment by vxlcoder** [comment]
done!

**Comment by vxlcoder** [comment]
The "fix" throws an exception (context not correct) when clicking the maximize button.

**Comment by vxlcoder** [comment]
see issue #509

**Comment by carter2422** [comment]
I believe we discussed this previously and decided not to tackle it due it it causing UI jumps. 

However, after extensively using it I've changed my mind. We should auto-hide the toolbar and properties when starting RetopoFlow because those areas are unusable while RF is active and show redundant information. 

Additionally, but not auto-hiding them we effectively make the good way to start RF to be from the hotkey menu, since that's the only way to get into a clean, maximized view.

**Comment by carter2422** [comment]
Just a note that this is done and working, with the exception of `Region Overlap` support.
