### ISSUE TITLE
 Retopoflow2.0 new problems

### ISSUE THREAD

**Issue by pianshanchou** [CGCookie/retopoflow#452]
Hello, there seems to be a BUG. Open the RF2.0 mode, the model can not be zoomed and rotated. My system is WIN10 blender2.79b Retopoflow2.0

**Comment by vxlcoder** [comment]
Thanks for the report, @pianshanchou, but I'm confused as to what the problem is.  You are not able to change the camera viewpoint when running RF 2.0?  Do you mouse/keyboard actions to navigate that are different from the Blender default?  Do you have any other add-ons installed?  What happens if you press the numpad numbers?  Does the view change?

**Comment by pianshanchou** [comment]
It looks like the model is frozen. I try to close all plug-ins, just turn on RF2.0, and the problem still exists. Running 2 can't change the camera view. The number of keyboards can not be used, and ESC can be used. 1.3 can be used normally.

**Comment by carter2422** [comment]
This sounds like a Blender configuration issue, perhaps related to your keymap. 

What keymap are you using and does RF navigation work if you Load Factory Settings and then enable?

**Comment by pianshanchou** [comment]
Thank you. I found the problem. I can change the system language from Chinese to English, so I can use it.^_^

**Comment by carter2422** [comment]
Ah! That is very good to know. 

Thanks!

**Comment by pianshanchou** [comment]
Thank you. RF2.0 is great. (∩_∩)
