### ISSUE TITLE
RetopoFlow wireframe

### ISSUE THREAD

**Issue by Larry3d** [CGCookie/retopoflow#465]
Hello everybody!

I have the following problem:

- RetopoFlow does not update to the latest version 2,0,0,1
My version is 2.0

- Although I get the message that I should restart Blender. But it stays with version 2.0

- When I start RetopoFlow, I see the mesh only in wireframe mode.

![retop_help](https://user-images.githubusercontent.com/38502179/38941429-da424792-432c-11e8-9e5a-7c6903f74957.jpg)

I have reinstalled the addon and start it from object mode.

- I see always the warning: Target polycount is high! RetopoFlow may load slowly.

thx

**Comment by carter2422** [comment]
@Larry3d you're on the correct version.

The wireframe problem is because you're activating the high-res object as the target. 

The workflow has changed a bit in 2.0; now the selected object will be the target and all other, visible, objects will be combined as the source. If you don't yet have a target object created then start RF without anything selected.

This is explained in more detail in the General and Tool Help.

**Comment by vxlcoder** [comment]
@Larry3d, also be sure to read through the Quick Start Guide by clicking the similarly named button in 3D View Tool Panel above the RF tools.

**Comment by Larry3d** [comment]
Thank you for your prompt reply.
Yes, it works now.

Thanks again.
