### ISSUE TITLE
Space Navigator disabled when switching to RF 2.0

### ISSUE THREAD

**Issue by RLSprouse** [CGCookie/retopoflow#472]
My Space Navigator works beautifully in Blender, but when I select a RF tool, it is disabled. The viewport navigation in RF is extremely awkward, almost unusable. For example scrolling my mouse wheel zooms in big increments so I can't really get where I want to be. Same with orbiting with the MMB - it is not at all smooth. Please support the Space Navigator!

**Comment by vxlcoder** [comment]
Thanks for the report, @RLSprouse.

By "Space Navigator", are you referring to 3Dconnexion's SpaceNavigator (now SpaceMouse)?  If so, I do not have one to optimize the RF experience directly, so I'll need your help with this.  Let me know if this is indeed what you were referring to, or if it is something else.

Separately, I'm confused about the notes on navigating using scrolling and MMB.  The navigation in RF using these buttons _should_ behave the same as in Blender, since I'm passing these actions through.  Do they behave differently?  Can you capture a video of this?

Thanks!

**Comment by vxlcoder** [comment]
@RLSprouse, I have added an advanced option to report the actions to the terminal.  This should print out any SpaceMouse actions, so I can know how to pass them along.  Also, I added an action `NDOF View Orbit with Zoom` which I had missed before (or was recently added?).  If the latter update doesn't fix the SpaceMouse navigation, the former will help us get it working.

Pull the latest `release/2.0.0` branch, or let me know and I'll pkg up a zip file with an updated RF.  Then, run Blender from terminal (xterm, cmd, console, etc.) and start RF.  Try navigating.  If it works, great!  let me know.  Otherwise, in Advanced section of options, enable the Debug Actions check.  Now, all of your reported to the terminal window.  Try using your SpaceMouse, and then copy-paste all of the `(..., ...)` reports to this issue on GitHub.  I'll use that info to add support.

Thanks!

**Comment by RLSprouse** [comment]
Hi Jon:

Yes, I was referring to the 3DConnexion SpaceNavigator. The model I am using is actually called a SpaceExplorer USB, but I think they all work the same way other than having more buttons etc.

I don’t know how to “pull the latest release” so if you could package a zip file and send it to me that would be greatly appreciated.

I think the trouble I was having with the MMB navigation was actually being caused by the mouse I was using. I found it difficult to press the MMB without simultaneously scrolling, vertically and/or horizontally. I just got a new mouse and it seems much more controllable, though zooming with the wheel still moves in big steps in Blender. I guess I am spoiled by the silky smooth movements I can do with the Space Navigator. Too I really look forward to helping you get that working in RF.

Thanks!

  ~ Russ

**Comment by Usuryname** [comment]
All input on my spacemouse except for the buttons outputs ('NDOF_MOTION', 'NOTHING')

Buttons seem to work though 
('NDOF_BUTTON_MENU', 'PRESS')
('NDOF_BUTTON_MENU', 'RELEASE')

**Comment by vxlcoder** [comment]
Thanks for the details @Usuryname!

@RLSprouse, can you search for `ndof` in the `Input` tab of your Blender Preferences?  Under `3D View`, do you see any other options than what I have in the screenshot below?  Especially notice the `view3d.ndof_orbit_zoom`, `view3d.ndof_orbit`, ...

![image](https://user-images.githubusercontent.com/3790699/41127435-ecb1f83c-6a78-11e8-9603-52acaef7f3cc.png)

**Comment by vxlcoder** [comment]
I've just pushed a commit that generalizes the navigation actions a bit.  @Usuryname, if you know how, could you try pulling to see if your NDOF input now works?  I cannot test here, so I might have broken it, too, especially with the various buttons that are available.

**Comment by Usuryname** [comment]
I tried the release 2.0.0 branch and it works with no problems. I'm using a spacemouse wireless so hopefully it works with others aswell.

Thanks heaps for the update.

**Comment by vxlcoder** [comment]
I believe this issue is fixed.  Please let me know if you have any other problems.  Closing for now!
