### ISSUE TITLE
Duplicate in search window?

### ISSUE THREAD

**Issue by Coverop** [CGCookie/retopoflow#479]
Hello.
So I noticed that, when I start a new blender file and search for any Retopology Function... I will get "faulty" function at first but when I search it again another function with the same name will appear.

Once I select the other function, tool starts to work.

**Comment by Coverop** [comment]
![blender_2018-05-15_09-45-37](https://user-images.githubusercontent.com/8415531/40043475-d88acb06-5824-11e8-8d70-28ab7ef7df50.png)

![blender_2018-05-15_09-45-59](https://user-images.githubusercontent.com/8415531/40043482-db00577a-5824-11e8-96e0-fc7497a2ae1e.png)

![blender_2018-05-15_09-46-08](https://user-images.githubusercontent.com/8415531/40043483-dcaeb68e-5824-11e8-8656-a2ca731abe7b.png)

![blender_2018-05-15_09-46-11](https://user-images.githubusercontent.com/8415531/40043487-de4b615e-5824-11e8-96b5-19543aeda1a4.png)

**Comment by vxlcoder** [comment]
Thanks for the report @Coverop.
Right now, RF 2.0 beta and RF 1.3 use the same names for the operators, so you'll see them in the space-menu twice.  This will be resolved once RF 2.0 is out of beta (where 1.3 tools will be removed/renamed).
As for the "faulty" function, I'm not sure what is happening there.  Could you post a video screen capture of starting Blender and then repeating what you've done in the images above?

**Comment by vxlcoder** [comment]
@Coverop, I have appended `1.3` to the names of all the 1.3 tools in order to make it easier to distinguish between the two versions.  Again, the 1.3 tools will be phased out soon.

I am still confused as for the "faulty" function you mentioned.  If this issue still remains, please open a new issue with details on reproducing the bug, and we'll take another look at it.

Thanks!
