### ISSUE TITLE
Viewport doesn't keep wire view settings [2.0]

### ISSUE THREAD

**Issue by nearsr** [CGCookie/retopoflow#484]
Here's how I setup my viewport so that I can see wire without interference from overlapping mesh:

Xray on
Matcap on (aesthetic)
When mesh is selected, in edit/object mode check "hidden wire" in the shading tab next to the matcap option

This works in native blender to allow me to see wire that is clipping through the mesh.
However, in the new retopoflow, these settings aren't preserved. Some of the bright white glowing wireframe clips underneath the mesh and can barely be seen. (Most prominent in curved areas when laying down large quads that will later be subdivided to surface closer to the mesh. These large quads go underneath and are hidden by the mesh.)

**Comment by vxlcoder** [comment]
Thank you for the report @nearsr.

At the moment, I'm not sure how to address this issue in a robust way.  OpenGL drawing (which is what we do for RF and what Blender uses) has many limitations, and this is one of those limitations.  As a compromise, I've exposed the transparency of the target mesh as options under General options.  Adjust this to suit your needs.

![target alpha](https://user-images.githubusercontent.com/3790699/41114614-eb451072-6a52-11e8-9a22-2ce538b3f33c.gif)

Also, try scaling all of the meshes up before starting RF.  Sometimes, that can help.

Please let me know if I misinterpreted your issue, otherwise I'm going to close the issue. (again, I am currently working on a more robust solution, but it's a hard problem!)
