### ISSUE TITLE
Wish for "harmony" of keymaps, between RetopoFlow 1.3.2 and 2.0.0 ?

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#493]
Hi all of you !

Yes, a wish... I use RetopoFlow in both versions 1.3.2 and 2.0.0.1, ans especially for the Polystrips tool.
I am ashamed but it is a little confusing for me, when I want to modify the number of segments !

I appreciate the (Shift + MouseWheel) key, or even the (Shift + +/-) key with 1.3.2... and wish to have the same possibility in 2.0.0.1, in addition to having (Shift + Up/Down arrow) key... Is that possible ?

About 2.0.0.1... there is a little "bug" : in the 3D view, the minus touch of the numpad  don't decrease the number of segments, but zooms out ! 
However, using the "-" button in the Options panel for Polystrips works fine... that's weird ! 

![minuskey](https://user-images.githubusercontent.com/38527057/41292556-381b4084-6e53-11e8-84f0-4333f2d5c249.jpg)

ILYA

**Comment by vxlcoder** [comment]
Thanks for the report, @ilyafr37.

The +/- buttons do actually increase/decrease the counts, but make sure you press the =+ and -_ buttons, not the numpad+ and numpad-.  The numpad buttons are typically bound to navigation (zoom in/out).  Alternatively, you can use Shift=/+ and Shift -/_.  We did change the shortcuts in 2.0 so that they can be consistent across all the tools and so they avoid default keyboard shortcuts in Blender (especially navigation shortcuts).

I've updated the tooltips to state Shift+Up and Shift+Down to avoid confusion.

Later, I will see about improving the UI further to make this easier and clearer and/or making the shortcuts customizable.

**Comment by ilyafr37** [comment]
OK Vxlcoder, I agree with you ! I don't use the numpad keys of the keyboard, but the alpha, like here : 

![keyboard](https://user-images.githubusercontent.com/38527057/41304389-4ae25d52-6e70-11e8-8b43-12e4f92f5598.jpg)

... but, but... the "+= }" key of the keyboard works to increase the number of segments, not the "6 - |" if I want to decrease the number of segments ! This key of the keyboard do nothing, it's what is my problem...

ILYA

**Comment by vxlcoder** [comment]
@ilyafr37, sorry for my late reply.

You can use shift+up and shift+down to adjust the segment count.

Or, start blender from console/terminal, start RF, under advanced check "Debug Actions".  Then, you should see in the terminal the keys that are pressed.  Try pressing your 6 key, and let me know what gets printed to the terminal.

![image](https://user-images.githubusercontent.com/3790699/42472924-08ce1ee8-8391-11e8-8f26-671390cc543c.png)

**Comment by vxlcoder** [comment]
I'm going to close this issue for now, @ilyafr37.  If you run into this issue again, please reopen and post the extra details I asked for in the previous comment.  Thanks!
