### ISSUE TITLE
Optimize Polystrips for speed

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#5]
Polystrips can quickly become quite slow, particularly on slower machines and complex models. 

If there's anything we can do to optimize it then we should :smile:

Speed is probably one of the more common points of critical feedback I've heard.

**Comment by patmo141** [comment]
Since the slowness which spawned this issue was related to ray_casting and snapping, not to Polystrips data structures, I think we have reached a point where the initial issue has been solved.  Perhaps more general optimization within the Polystrips and Contours data structures should still be an enhancement task which we can reference in commits.

**Comment by carter2422** [comment]
Agreed. Closing.
