### ISSUE TITLE
Blender freeze 100% on draw contours

### ISSUE THREAD

**Issue by miecz** [CGCookie/retopoflow#532]
Blender always freezes when I attempt to draw a horizontal contour in the attached file (a quilted jacket). I've decimated the jacket to make it easier for RetopoFlow to work with. At first I thought it was because of the X symmetry, but I've tried it without using the symmetry as well. The effect is the same - a 100% chance for blender freeze. 

My system specs:
Blender version: 2.79.
CPU: Inter core i7-6700
Windows 10 64 bit
32GB RAM
nVidia GeForce 970 GTX

![retopo freeze 100 percent](https://user-images.githubusercontent.com/12141119/42891913-c456520e-8ab0-11e8-9c78-d5616aca362e.png)

[RetopoTests.zip](https://github.com/CGCookie/retopoflow/files/2206381/RetopoTests.zip)

Hope it helps!
Maciej

**Comment by carter2422** [comment]
Thanks for the test file @miecz! We'll try and replicate it and get back to you.

**Comment by vxlcoder** [comment]
Thanks for the report, @miecz!  The .blend file is very helpful!

Ironically, I believe the problem is that the source mesh has some really bad topology.

I know, RF is designed to improve the topology of the source.  However RF uses the source's topology to solve some of the problems, especially with Contours.  In this case, Contours uses a walking algorithm to find out what all needs in the contour cut, and your mesh has many non-manifold edges (causes problems with our walking algorithm).  It looks like you might have used the remove doubles command at one point.

To get you moving forward quickly, one workaround to get you up and going again is to apply a remesh operator (use smooth mode and high octree setting, like 11).  This will clean up the topology so RF doesn't get stuck, but shouldn't modify the geometry too much.  Note: I'm not entirely certain this will fix the problem, but it might get you started.

I will take a look at the walking algorithm to see if we can handle better these cases, at least to prevent getting stuck and warning the artist of bad source topology.

Thanks!

**Comment by miecz** [comment]
Great! I'll try the workaround. But this mesh is a result of a remesh operator actually. It's a mesh from Marvelous Designer. I guess remesh didn't to a good job here :). I didn't check the mesh after it. I'll solve the issues with the mesh itself and test contours again. Thanks!

**Comment by miecz** [comment]
I'm just letting you know that I've fixed all non-manifold areas on the mesh (with a crazy combination of Instant Meshes / Remesh and manual fixing ;) ). RetopoFlow runs smooth on a 1M mesh (I will stress test it soon ;) ). Your tool is a life saver! I was not a huge fan of retopology, but now... I love it! I've managed to get a decent retopo of that jacket in around... 10 minutes!

**Comment by vxlcoder** [comment]
I'm glad to hear that the workaround worked, @miecz!  If possible, we would really like to see your final retopo!

I will take another look at the walking code in Contours to see how this freezing can be prevented in the future.

Let us know if you have any other problems!
