### ISSUE TITLE
RF mode shrinkwrap offset

### ISSUE THREAD

**Issue by Nocturael** [CGCookie/retopoflow#564]
![screenshot 2018-07-30 21 56 41](https://user-images.githubusercontent.com/2722361/43420634-b0e4acaa-9444-11e8-8db8-4c8f9671306c.png)
![screenshot 2018-07-30 21 56 55](https://user-images.githubusercontent.com/2722361/43420635-b103b2bc-9444-11e8-8647-ae4ea54c58b3.png)
When entering RF mode, the offset's too much. Suggestion: make it adjustable.

**Comment by vxlcoder** [comment]
@Nocturael, I exposed an option under General > Target Rendering > Normal Offset that allows you to adjust how far each vertex is rendered away from the source.  Note: this is only for improving visualization; it does not alter the vertex's position!

![normal offset](https://user-images.githubusercontent.com/3790699/43427227-b3397d5a-9426-11e8-8da7-a2520ed5bd8f.gif)

**Comment by Nocturael** [comment]
Works for me, thanks. :)

**Comment by JoseConseco** [comment]
Projection offset would be cool though. Often if you retopo mesh, it is bit smaller that hipoly geometry. Offsetting retopo mesh along normals parameter, would be nice option to compensate for it.

**Comment by vxlcoder** [comment]
Thanks for the suggestion, @JoseConseco.

I've made a few changes in fb7d0b9 that do this through a displacement modifier.  It wouldn't make much sense to actually move the target's verts away from the surface, because that would cause the verts to move every time you modify the target in RF, exit RF, enter RF, modify, etc.  In other words, it wouldn't be very stable or predictable.  Instead, doing this through a modifier, the verts don't need to move away from the surface.

Of course, you can always apply the modifier on your own.

Closing this issue.
