### ISSUE TITLE
Slow even with a simple sphere.

### ISSUE THREAD

**Issue by rt974** [CGCookie/retopoflow#633]
This is freezing and slow on a sphere with 2 subdivisions applied.

Before that i tried with a sculped model 2 million polys. Unusable.

Conclusion : Use Maya live mode with quad draw, Houdini or Blender's basic tools and forget retopoflow.

**Comment by radeonoff** [comment]
same here. in order to study and use RF i have to reduce polycount on my char sculpt to ~370k tris with 
Zbrush decimation and now it doesn't look so good. Also there are huge fps drop with symmetry enabled. 

RF 2.0.0
Blender 2.79
GeForce GTX 970
Win10

addons
UE4 tools
AssetGen
many insignificant other like F2, node wrangler, pie menu, etc

**Comment by jlampel** [comment]
I'm not able to replicate the original issue. Nonetheless, improving performance will be one of our main focuses going forward. If you have issues in v3.0+, please open a new issue. Thanks!
