### ISSUE TITLE
Unable to activate retopoflow in 2.79b

### ISSUE THREAD

**Issue by prophet067** [CGCookie/retopoflow#651]
After installing from zip I get this error:
![retopoflowerror](https://user-images.githubusercontent.com/44552645/47619732-2201d200-da9f-11e8-8788-cb916947ce81.jpg)
Please help!

**Comment by prophet067** [comment]
I unfortunately paid for this program, does anyone still work on it?

**Comment by carter2422** [comment]
@prophet067 apologies for the delay. @vxlcoder is our key developer and he's been out traveling for the Blender Conference. 

Since you're getting a DLL load error then it's a fairly safe bet that the problem is due to a bad copy of Blender installed. Did you compile it from source?

My suggestion is that you re-install blender 2.79b from blender.org and then try activating RetopoFlow again.

**Comment by abramsor** [comment]
I had the same issue yesterday when  I downloaded the latest daily build.  Had reinstall 2.79b to get it to work.

**Comment by carter2422** [comment]
@abramsor yeah it seems there's a library that's not being included in the daily builds that's necessary for RetopoFlow to start.

**Comment by prophet067** [comment]
Okay, I will try this and get back to you. Thanks for the response

**Comment by prophet067** [comment]
I just used the downloader from blender.org to remove my copy of blender. I then re-installed using the same one and I am still getting the exact same error

**Comment by prophet067** [comment]
I found my blender preferences in user/appdata/roaming and deleted it. I then started blender as an admin and it worked!

**Comment by carter2422** [comment]
That's great to hear @prophet067! Thanks for letting us know.
