### ISSUE TITLE
PolyPen: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by 0liviah** [CGCookie/retopoflow#662]
I was just trying to use the PolyPen. I was able to draw as much as 1 edge, then this happened (twice in a row actually, because I tried to use the tool again.). Also, the add-on really slows down Blender, but it's definitely useful.
Edit: I didn't report it both times, just the first one.

![image](https://user-images.githubusercontent.com/45232835/48923177-1a113400-ee8b-11e8-985e-3af8ae978846.png)

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 7, 6.1.7601, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: ATI Technologies Inc., AMD Radeon HD 7800 Series, 4.5.13474 Compatibility Profile Context 22.19.162.4, 4.50
- Timestamp: 2018-11-22 19:09:45.934443


Error Hash: 9a42177a85e4c84a725eab0bc42f53aa


Trace:

- EXCEPTION (<class 'ValueError'>): edges.new(): this edge exists
- .../rfmode\rfmesh.py
- 000 1331:new_edge() bme = self.bme.edges.new(verts)
- .../rfmode\rfcontext_target.py
- 001 0396:new_edge() return self.rftarget.new_edge(verts)
- .../rfmode\rftool_polypen.py
- 002 0282:modal_insert() bme = self.rfcontext.new_edge((bmv0, bmv1))
- .../rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0110:modal() nmode = self.FSM[self.mode]()
- 005 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 006 0556:modal_main() self.tool.modal()
- 007 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
This is the same issue as #603, and it should now be fixed in the latest version of `release/2.0.1` branch. 
 If you know how, feel free to test that version, otherwise it will be officially released soon.

I'm closing this issue, but reopen if you continue to have problems.

@0liviah, as for the slow-down, can you please open a new issue and let us know what you do when it starts to slow down?  These are two separate issues, and I'd like to narrow that problem down, too.

Thanks for reporting this issue!
