### ISSUE TITLE
high inconsistency with grease pencil entering RetopoFlowMode

### ISSUE THREAD

**Issue by Sodazer0** [CGCookie/retopoflow#670]
Sketching directly on the surfaces of mesh_objects is a big part of my modelling work-flow.
Unfortunately all greasepecil-strokes inherit a strong offset in  location and scale as soon
as I am entering RetopoFlowMode.

I just uploaded a small videoShot of that behaviour.
I hope you feel a deep urge to tackle down this issue ;D

http://tinyurl.com/y9mxdfhf

**Comment by vxlcoder** [comment]
Thanks for the helpful video!

Right now, RF has basically zero support for anything other than meshes.  In fact, when starting RF, RF will rescale the mesh to fit in a bounded box so that all of our visualizations work uniformly, regardless of the scale of the original source/target.  This is why you see the grease pencil annotations shift/scale.

I'll have to think a bit more about how to get this to work.

**Comment by Sodazer0** [comment]
Thank you for your very fast reply,

Is it possible to tell the exakt size in Blender_Units?
maybe I can use that to find a walkaround the issue for now at least.

Also,
are there any particular intressts from your side to implement a propper "on mehs sketching grease pencil style" to Retopoflow?

And,
since in 2.8 greace pencil strokes are now represented as real object, will it be esiear from that to find a solution for grease-pencil-inconsistensy within RetopoFlowMode?
Just curious...

**Comment by jlampel** [comment]
Circling back on this, the scale for the RF bounding box is 100 x 100 meters. I'm going to close this out, but I'll create a new issue to collect all scaling related problems so we can address them all in one place.
