### ISSUE TITLE
Inconsistency between mesh preview when retopoflow is turned on and the final mesh.

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#677]
Hello, I began retopology of my model and I ran into an issue that doesn't allow me to see what retopology mesh looks like in reality.

With retopoflow turned on the retopology mesh looks like this: https://imgur.com/bkMrrEs
When retopoflow is turned off the retopology mesh looks like this: https://imgur.com/FrdhXLn
As you can see it's impossible to retopology the model with such inconsistency between each view. I should have seen what showed in the second screen when retopoflow is turned on. 

Perhaps there is a setting that I'm not aware of to fix that issue?

**Comment by LunarOrbiter77** [comment]
Hi Lewiatan45.
That's exactly the same problem i have. Would you let me know if there is a way to fix it?

Best regards.

LunarO.

**Comment by vxlcoder** [comment]
Thanks for the report, @Lewiatan45.

I believe this issue is related to issue #667 (and #643).

I'm still working on a good solution for this, but for now you can workaround this visual bug by either scaling your mesh up (say 10x or 100x) before entering RF, or decrease the Normal Offset (RF -> Options -> General -> Target Rendering -> Normal Offset).

If you have more info that makes this a distinct problem, please let me know so I can work on a better solution.

**Comment by Lewiatan45** [comment]
I figured out the workaround with scaling the model up 13 times and applying the scale. 

Wouldn't be just more simple if there was a setting that tells how high above a mesh should be a retopo mesh? I couldn't find such feature.

**Comment by vxlcoder** [comment]
The normal offset I mentioned above does this. Working on finding a better solution, though.

**Comment by carter2422** [comment]
I'm closing this since there's no real bug here, merely a lackluster method of displaying the mesh offset.
