### ISSUE TITLE
RetopoFlow B280 Error on activation

### ISSUE THREAD

**Issue by SavMartin** [CGCookie/retopoflow#705]
I get this error msg, when i try to activate RetopoFlow  branch 280 in Blender 2.80.44,sorry if this is not the rigth place to post this issues.. 
Im on linux mint 19.1
![imagen](https://user-images.githubusercontent.com/30030642/52958755-a51ba080-338c-11e9-8209-dd10019151ba.png)

**Comment by vxlcoder** [comment]
Thanks for the report, @SavMartin.

Right now, the `b280` branch is very much a work in progress, and it probably won't be fully functional for some time (still working on a timeline).  In fact, I have a considerable number of changes sitting on my machine right now that I haven't even committed yet, because the change is extensive and still in process.

When it is ready to test, we will definitely get the word out.  And you're free to test it now.  Just assume that nothing really works in Blender 2.80 quite yet :)

**Comment by SavMartin** [comment]
Thanks for your answer, I'm going to try every time you put a new update.
Are you interested in publishing if they work for me or not, or do you prefer that I wait to publish errors when you think it is functional?

**Comment by vxlcoder** [comment]
That's a great question, @SavMartin.  At the moment, you should assume that things are just plain broken, and so reporting issues probably won't be helpful.  During this time, I will be pushing up WiP commits just to sync between machines, which means that you'll see lots of activity on this branch.  I have a few ongoing threads of development that I'm following through on, mostly restructuring and refactoring to use CookieCutter, but also fitting RF for 2.80.  It will take a while to get everything off the ground and into a testable state.  If you follow me on twitter (https://twitter.com/gfxcoder) or CGCookie (https://twitter.com/cgcookie), we will tweet when we're closer to an alpha and when reporting issues would be helpful.  Thanks for your willingness to help!  I'll definitely appreciate it when RF is in running order again!

**Comment by SavMartin** [comment]
Ok.

**Comment by vxlcoder** [comment]
closing this issue for now.  please let us know if you have any other issues.
