### ISSUE TITLE
Relax tool

### ISSUE THREAD

**Issue by grimakaka** [CGCookie/retopoflow#725]
sometimes relax tool behaves strangely.
![bugRelax](https://user-images.githubusercontent.com/50794359/58660851-13c6ad80-832f-11e9-888b-3376b71a02b9.gif)
[bug_relax.zip](https://github.com/CGCookie/retopoflow/files/3238581/bug_relax.zip)

**Comment by vxlcoder** [comment]
thanks for the report, @grimakaka!

this issue is related to issues 514 and 657.

the short answer is: this is a very difficult problem to solve in a general case.  I plan to revisit the math/algorithm here once RF is working in blender 2.80.

in the mean time, have you tried adjusting the brush properties under Options > Relax > Brush Properties > Advanced?  Sometimes changing these can have a positive impact on results.

![image](https://user-images.githubusercontent.com/3790699/58718587-d2b8b280-839b-11e9-8cec-a84824b87af5.png)

**Comment by grimakaka** [comment]
Thank you for the answer! Sorry, I did not know that I duplicated the problem. If you know this problem, then this branch can be removed.
