### ISSUE TITLE
How to install old version of Retopoflow?

### ISSUE THREAD

**Issue by Octave1201** [CGCookie/retopoflow#773]
Hi everyone!

Please, can someone explain me how to install an old version of Retopoflow?

https://github.com/CGCookie/retopoflow/releases

When I would like to install Retopoflow 1.3.2.zip, but when I install, Blender can't read it...

Thanks in advance for your help...

**Comment by vxlcoder** [comment]
GH's zipping does not create folders how Blender likes them.  instead, use the following zip

https://www.dropbox.com/s/5qhf9tyeqdrybus/RetopoFlow_v1.3.2.zip?dl=0

**Comment by Octave1201** [comment]
Thanks... But when I install your addon, I got this message 

Missing script files: Retopoflow-master

https://zupimages.net/viewer.php?id=19/49/e881.png

**Comment by vxlcoder** [comment]
I believe that is from the previous version you tried installing. Try
uninstalling that addon. Also try loading factory settings, then install my
version. Let me know if you're still having problems.

**Comment by Octave1201** [comment]
The installation is OK now (Missing script files: Retopoflow-master doesn't appear anymore) but unfortunately, I still can't grab the Green handle with the RMB :(

https://github.com/CGCookie/retopoflow/issues/770

**Comment by carter2422** [comment]
@Octave1201 part of the problem is that the Github releases are not packaged in such a way as to enable direct installation in Blender. Those are simply the code tags to reference the specific version in the commit history for that release. 

If you've purchased RetopoFlow then please download 1.3.2 from your Blender Market account at https://blendermarket.com/account/orders
