### ISSUE TITLE
Add Restore ability to Polystrips

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#78]
If Polystrips crashes right now we lose everything. As discussed, we need to implement the cache from Contours into Polystrips. Or implement an even better, new cache for both.

**Comment by patmo141** [comment]
fixed by commit 71c3298.

Ctrl + Z after cancelling or error will restore all but the last operation the user completed.
There is the possibility that if the user changes the target mesh, and existing geometry was being used that an error will occur.
Changes to the source mesh will invalidate and cause the cache to be cleared. 
We should alert users to this behavior or possibly add snippet at bottom of help text
