### ISSUE TITLE
Some Contour transforms do not work in orthographic mode

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#780]
If you attempt to grab or rotate a symeterized loop (loop cutting across the symmetry line) in Orthographic view, from Side view, then the transform does nothing from. No errors thrown.

Rotating works from front/back view, but not side. If you rotate far enough then the loop eventually snaps to a distorted angle.
Grab does not work at all in ortho on symmetry loops.
Everything works as expected in perspective.

Video:
https://share.getcloudapp.com/jkunL8WQ

**Comment by vxlcoder** [comment]
most of these issues should now be fixed!

however, the problem around 0:07 in the video is something different.  notice that the origin of the loop/strip (left end of the yellow gizmo) is actually behind the hand.  when manipulating loops/strips with contours, the origin and normal are projected to the screen, then they are manipulated according to what the artist is doing (grab/slide/rotate), then they are unprojected (raycast) back into 3D space.  then some crawling and other things happen to manipulate the selected points accordingly.  but the main point is this: if the origin unprojects to the wrong place, then either contours ignores it (which is what you are seeing) or it snaps the selected loop/strip to the "wrong" part of the source.  so that hand wasn't there, or the origin was further back (not occluded by hand), rotating would have worked.  (something has to be visible for most of these tools to work.  in this case, it needs to be the origin of the loop/strip)

![image](https://user-images.githubusercontent.com/3790699/71795343-bce72c00-3013-11ea-9cbf-3a9a6f448b62.png)

instead of ray casting back to the source, we could use nearest surface, but then other weird things can start happening (think: using shrinkwrap with edit mode to do retopo)

**Comment by carter2422** [comment]
That makes total sense @vxlcoder. I suggest we open that as a *known issue* and set it aside for a latter date. 

Everything else is working great!
