### ISSUE TITLE
[QUESTION] What happened to ability to select a spefic mesh as a target for retopoflow? 

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#790]
**Retopoflow Version:** 
3.0.0a

**Blender Version (Hash):** {blender version hash here}
2.81a 
**Platform:** {platform here}
Windows 10 64Bit

**Issue:**
Hello, 

I use Blender 2.81a with  Retopoflow 3.0.0a plugin. 
I noticed I can't select a specific mesh as a "target" like it used to be in retopoflow for Blender 2,79c. 
So I have an entire cage completed for my dragon model that's now useless because I cannot select that mesh as a retopoflow target and continue working on it in retopo mode. 
I also noticed Retopflow kinda forgot that newly created mesh target was used for retopo so now when I select high poly mesh, the only option I have is to create a new target, instead of working on the old target.

**Comment by vxlcoder** [comment]
@Lewiatan45, the workflow has changed just a bit for RF 3.

Now, in order to continue working on a previous target, first select the target, switch to Edit mode on that target, then then start RF.  All other visible meshes will act as source mesh.  Be sure to check out the Quick Start Guide, but you can also ask additional questions via the Blender Market.

Thanks for trying out RF!

Closing this issue.

**Comment by Lewiatan45** [comment]
Oh, thank you a lot, I didn't know it works this way now :)
