### ISSUE TITLE
PolyStrips: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by laridk** [CGCookie/retopoflow#792]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.Below are a few notes that will help us in fixing this problem.

- Provide as much information as you can so that we can reproduce the problem and fix it.
- Screenshots and .blend files are very helpful.
- Change the title of this bug report to something descriptive and helpful.

Thank you!

```
Environment:

- RetopoFlow: 3.0.0α
- Blender: 2.82.7 master 2020-02-12
- Platform: Darwin, 19.0.0, Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64, x86_64, i386
- GPU: NVIDIA Corporation, NVIDIA GeForce GTX 775M OpenGL Engine, 4.1 NVIDIA-14.0.31 355.11.11.10.10.143, 4.10
- Timestamp: 2020-02-20 19:17:07.571636
- Undo: stroke, select and grab, select and grab, select and grab, select and grab, select and grab, select and grab

Error Hash: 6dda22a701aa352d035a9ca96c179158

Trace:

- EXCEPTION (<class 'RuntimeError'>): Error: Cannot open file RetopoFlow_backup.blend@ for writing: Read-only file system
- 
-     /Applications/Blender.app/Contents/Resources/2.82/scripts/modules/bpy/ops.py
- 000 0201:__call__() ret = op_call(self.idname_py(), None, kw)
-     /Users/laridk/Library/Application Support/Blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_blender.py
- 001 0391:save_backup() bpy.ops.wm.save_as_mainfile(filepath=filepath, check_existing=False, copy=True)
- 002 0368:check_auto_save() self.save_backup()
-     /Users/laridk/Library/Application Support/Blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_states.py
- 003 0124:modal_main() self.check_auto_save()
-     .../common/fsm.py
- 004 0063:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @laridk.

It seems that you do not have permission to write files in the folder that Blender thinks is good for temp files.  Unfortunately, the error message does not specify the path here.  If you are using a lab machine, or you are logged in under a restricted account, this could be the case.

I've made some changes in commit d492d72 that handles this more gracefully.  The problem still exists, but you'll be greeted with a much nicer message with better details on what went wrong.

If you can, try using the latest commit of `b280` RF to see what info you get.

Otherwise, a workaround is to disable backup (Blender > Edit > Preferences > Save & Load > Auto Save Temporary Files) until we release the next version of RF.

Thanks again!
