### ISSUE TITLE
what is this? after this. I can't use middle click.

### ISSUE THREAD

**Issue by labica** [CGCookie/retopoflow#816]
what is this? after this. I can't use middle click.

blender 2.83 and retopoflow 3.0 beta

![image](https://user-images.githubusercontent.com/6257391/80915558-0bbc8c80-8d8e-11ea-8a2b-5f1a73e949ca.png)

**Comment by vxlcoder** [comment]
Thanks for the report, @labica. 

This bug was recently fixed, but we have not yet released it in an official beta, yet.

If you know how to install from GH, pull the latest version.  Otherwise, you can use a simple workaround by enabling Region Overlap (Blender > Edit > Preferences > Interface > Editors > check Region Overlap).  we'll release a new version will the fix very soon.

**Comment by labica** [comment]
check Region works. thank you.
