### ISSUE TITLE
[BUG] Smart select loop breaks after dissolving nearby outer edge loop

### ISSUE THREAD

**Issue by knorthfe** [CGCookie/retopoflow#837]
Retopoflow Version: 3.0 beta 2

Blender Version/Hash: 2.82a

Platform Version/Distribution: Windows 10 Pro

**Issue:**

When an edge loop that is part of the boundary of a retopo mesh is selected and dissolved, the edge loop closest to it becomes unselectable using double click afterwards.

**How to Reproduce:**

![steps](https://user-images.githubusercontent.com/1375891/83008082-3c34c680-9fda-11ea-8712-2e4be7e15145.png)

1. Give retopo object at least three edge loops so you can dissolve one edge loop while having some remain
2. Select an edge loop that is not part of the "inside" of the mesh and dissolve it
3. The edge loop closest to the one you dissolved will now be unselectable by double clicking

Notes:

- I did some testing and this was found by using contours but the selection aspect is affected with all tools. 
- I use left click select but right click select is also affected.
- If you hit x and instead of dissolving the outer edge loop do "delete only edges/faces" and then "delete vertices" the bug doesn't happen and you can still select the edge loop

**Comment by vxlcoder** [comment]
Thanks for the report, @knorthfe.  Will take a look at it!

**Comment by vxlcoder** [comment]
actually, this is (unfortunately) intended.

when you dissolve that top ring of vertices, it will "delete" the top ring of vertices and create a face in the middle ring of vertices.  this also happens in blender.  what this means is that the middle ring of vertices (now top) is actually the vertices around an ngon.

this is unfortunate, because it is a counter-intuitive operation for retopology but legitimate operation for general modeling.  so, i'm not entirely certain what should happen here to fix this other than saying "don't do that", which isn't satisfying at all.

one option that i'm considering is having a checker run across the meshes that looks at the "integrity" of the target mesh.  for example, it can highlight non-manifold edges, faces that poorly capture the source details (such as this issue), disconnected verts/edges, etc.  having a sanity or integrity checker would help capture this, but it's still only an idea.

**Comment by vxlcoder** [comment]
considering other options to tackle this problem more generally...

**Comment by knorthfe** [comment]
Thanks for the response! I hadn't checked to see what the retopo mesh looked like after the operation and I didn't realize it was creating an ngon after the fact. 

That being said, you _can_ select the vertex loop afterwards in Blender but not Retopoflow. I noticed the selection options are different depending on the tool (can't do loop selects with the PolyPen tool for example) and coming from other retopo software I expected selection operations to be similar to Blender itself. I realize some of these selections may not make sense for the given tool type, but it would help with being able to do things like fix topology without having to leave retopoflow or have to remember which tools can select which way.

In any case, thanks for the clarification, I'll be more careful about dissolving edge loops!
