### ISSUE TITLE
[QUESTION] Does ReptopoFlow 3 beta 2 work with Blender 2.83?

### ISSUE THREAD

**Issue by dsguffey** [CGCookie/retopoflow#848]
I used this guide to install: https://www.reddit.com/r/blenderhelp/comments/eljxj8/short_guide_on_getting_retopoflow_30_to_work_from/
My version came from here: https://github.com/CGCookie/retopoflow/releases/tag/v3.0.0-beta-2

When I tried to add it to Blender 2.83, it told me it was broken because I'm using the wrong version. Does my version of Reptoflow work with Blender 2.83? If not, is there a more current version I should use? Otherwise, I'm not sure what I'm doing wrong.

**Comment by vxlcoder** [comment]
Hi  @dsguffey!

I'm not sure what you mean by "it told me it was broken because I'm using the wrong version".  Can you post a screenshot?  The latest version of RF (3.0 beta2) does work in Blender 2.83.

Keep in mind that downloading zips directly from GitHub can be very tricky to get correct.  And unfortunately we aren't supporting this method, because: 1. everyone's system is a little different, 2. Blender and Python are _VERY_ particular about naming conventions and file structures, and 3. the steps involved with that method must be followed perfectly.

Note: the zip that you get with a Blender Market purchase will install without a hassle.

If you're a developer and are familiar with git, the easiest way is simply following the directions in the README at the root of `b280` branch.  Otherwise, you can try following the very sparse instructions on that guide (and read through the comments!).  Just make sure that you follow them perfectly!

**Comment by dsguffey** [comment]
Yeah, it's probably the file system. I've had that issue with addons in the
past. It's weird to me that some video games are more forgiving about file
structures in their mods than Blender, but se la vie. Not to look a gift
horse in the mouth, but if you have a zip that just works straight out of
the box, why not provide that to everybody? Do you only want feedback from
seasoned professionals and don't want to hear from n00b hobbyists like me?
The entire reason I'm looking at RetopoFlow in the first place is because
I'm just not that skilled and I'm looking for tools to make things easier.

**Comment by dsguffey** [comment]
I'll answer my own question. For some strange reason, Blender decided to install the addon into the 2.82 directory instead of creating a 2.83 folder and putting it there. I created the directory myself, copied it over, and it worked fine.

**Comment by dsguffey** [comment]
I'll answer my own question. For some strange reason, Blender decided to install the addon into the 2.82 directory instead of creating a 2.83 folder and putting it there. I created the directory myself, copied it over, and it worked fine.

**Comment by vxlcoder** [comment]
That's very strange about installing in wrong folder, @dsguffey.  I'm glad to read that you figured it out!

re: feedback: we _love_ reading the feedback from all artists that use RF, whether pro or just starting off, because we designed this add-on for them!

re: providing a zip: The quick and simple answer is that our primary distribution is through the Blender Market.  We have poured a great deal of time and energy into developing an add-on to solve a challenging problem, and we're very proud of the product. 
 However, we do know that some artists/devs have reasons not to purchase a copy and support future development: just trying it out, can't afford it, still in school, etc.---that's part of the reason why this repo is publicly available (and not just available after purchase).

For the casual drive-by testers, we are happy that you're trying out RF, and we hope it works for you.  For those artists that use RF and have some feedback that will help the community, we're all ears!

I hope that was helpful.  Please let us know if you have any other problems or feedback!
