### ISSUE TITLE
[QUESTION] How do you mirror a local axis instead of a global one in Retopoflow 3?

### ISSUE THREAD

**Issue by dsguffey** [CGCookie/retopoflow#849]
Using: Retopoflow 3-beta-2 in Blender 2.83. I have a high poly asymmetrical model. The line intersecting the model and a global axis is handy, but it would hugely helpful if I could alter the flow of that line to appropriately mirror across a model that has already been posed and is no way symmetrical across any global axis. Is there any way to do that, or do you have to manually adjust the rotation of the model outside of RetopoFlow to center each part of the model to an axis one bit at a time?

![Magik Asymmetrical](https://user-images.githubusercontent.com/65681495/85902728-b7a0b800-b7d2-11ea-9488-b0c13ad0ace3.JPG)

**Comment by vxlcoder** [comment]
The mirroring is based on the target object's frame (origin/location and rotation). this is exactly the same as Blender's mirror modifier.

So, you can try moving the target (low-resolution retopo mesh) to the left so the origin is closer to the center of your object.  Otherwise, you might have to model the source without symmetry.  (will need to do that for the hands, lower legs, and hair anyways due to high antisymmetry)

Right now, RF does not handle asymmetric symmetry (most applications don't... very hard problem in general), but we have a few ideas on tackling this problem in the future.

**Comment by dsguffey** [comment]
Man, half my issue in Blender with the forums is just figuring out the right way to ask a question. When I said "local," I meant local to the face of the model (for example), not local as in the object's frame. That lack of clarity on my part has caused me days of getting answers to my questions that don't work and this is the first time I realized why I was getting those answers.  What I'm getting from you is that I'm basically wasting time trying to use mirror on this model, given it's nature. It'd be faster for me just to do the whole thing myself. Can I get a bit of general advice from you? How important is symmetry for animation? Would I be better off just starting off from scratch with a whole new symmetrical sculpt that I can easily mirror? Or is it fine if I don't have aesthetically pleasing mirrored edge loops? My first attempt is pretty ugly looking:

![Retopology - my first attempt](https://user-images.githubusercontent.com/65681495/85909853-ef672a00-b7e9-11ea-8587-c3a78cef0e18.JPG)

**Comment by dsguffey** [comment]
The solution to my issue is that you mirror an empty object in Blender and then rotate it until the mirror is working properly. As far as I can tell, mirrored empties bug out in RetopoFlow, so it's best to just wait and mirror in Blender after you've finished using Retopoflow to do one side of the thing you want mirrored. Apply mirror and go back to RetopoFlow to if you want to continue using the same mesh.
