### ISSUE TITLE
[BUG]Increase/Decrease segment count doesn't work in every case

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#861]
Retopoflow Version: 2.0.3

Blender Version/Hash: 2.79.7

Platform Version/Distribution: Windows 7 SP1 Integral Edition, 6.1.7601, AMD64, Intel64 Family 6 Model 26 Stepping 5, GenuineIntel

&nbsp;

**Issue:**

Hi all of you !

Here is what I observe with the Contours tool (Q) : 

- Decrease/increase segment count with Shift Down or Shift Up, works ONLY for the first drawn edge loop. That don't work for example if I select all the retopologized form.
- I have the very same observation with Equals : it works only with the very first drawn edge loop.
- Minus doesn't work at all...

Thanks in advance if you can solve this annoying bug, or explain me may be, what wrong action is mine !

ILYA

**Comment by vxlcoder** [comment]
Thanks for the question, @ilyafr37.

Yes, you can only change the cut count on the very first cut, because it isn't clear how to change the count when the mesh becomes more connected.  Instead, you can use the Loops tool to add or remove loops/cuts.

Note about the minus: the numpad minus is different from the top-row minus above the P key on US keyboards.  Contours only watches for the top-row minus, not for numpad minus.  (numpad minus is usually used to dolly the view out, and numpad plus for dollying in)

**Comment by ilyafr37** [comment]
Hi Jon !

Thanks a lot for your answer, first of all !
I agree with you, the "right" minus touch to use is the top-row touch, OK.
It's what I do without any effect... but... reading your answer, I have an
idea, may be a stupid one but I try to mention it !
My keyboard is a french one, not an US, because I'm french... would it be
why the top-row minus touch (fot me, above T and Y touch) doesn't match ?

Friendly yours !

Le mar. 29 sept. 2020 à 03:15, Jon Denning <notifications@github.com> a
écrit :

**Comment by jlampel** [comment]
Hmm, the keyboard layout could make a difference but only if it's mapped differently in Blender as well. Closing this out since Shift scrolling should work in any region
