### ISSUE TITLE
Poor performance in Retopoflow 3.0.0 RC1 [FEEDBACK]

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#873]
Retopoflow Version: 3.0.0 RC1
Blender Version/Hash: 2.90.0
PC: i7-6700k 4,40 GHz, 48GB RAM, MSI GTX 1080 8GB VRAM.

**Issue:**
The poor performance of UI and retopoflow tools used on 3 600 000 mln high poly mesh. 

Hello, 
I was curious if this update did something to improve performance so I opened the model that through the pain I managed to retopo fully with the previous version of this plugin (the low poly mesh has 36 000 polygons), and it turned out the update did little to nothing regarding performance. 
It is especially noticeable with a tweak tool that gets the position updates every 2-3 seconds when I move vertex with that tool around. PolyPen takes 1-2 seconds to fill 4 vertexes to create a new polygon. You'd also notice the interesting behavior of the Relax tool (origin of both meshes are at the same spot, in the middle of the mesh).

Due to the fact this tool cannot handle even such high poly mesh, it makes this plugin useless for me. I make creature models that require high poly meshes to get all details during the normal maps baking process.

{*add any screenshots of the issue here*}
Recorded performance of Tweak Tool and UI
https://imgur.com/JhfNycn

**How to Reproduce:**

- Have a high poly mesh ~3 600 000 polygons
- Enable Retopoflow on a finished low poly mesh. 
- Open retopoflow tools 
- Observe performance.

**Comment by vxlcoder** [comment]
Thanks for the update, @Lewiatan45. 

There is something very different about your setup that I haven't seen.  Your machine is more than capable.  Would you be willing to share your .blend file?  You can email to retopoflow@cgcookie.com.

I'm running even more stressful tests now.

**Comment by vxlcoder** [comment]
I think I might have figured out the problem.

do you only have problems on really big meshes? can you open the task manager or system viewer to see how much memory is used/free, especially virtual or swap memory.

**Comment by Lewiatan45** [comment]
I may send the blend file later today or in the evening.

Yes, Retopoflow gets extremely slow with a few million polygon meshes; it is noticeable as I work on retopo.

When Retopoflow is on it the RAM usage is increased to 23% (It uses 4,8GB RAM)
When I use tweak tool GPU is used in 5-9% https://imgur.com/dqgjFNa

**Comment by Lewiatan45** [comment]
I sent the mail with a link to a blend file @vxlcoder

**Comment by vxlcoder** [comment]
Thanks for the file, @Lewiatan45!

This is a use case that we have not considered as much, and unfortunately it really shows in RF's performance.  RF runs well when the high resolution source meshes are <1m triangles and the low resolution target mesh is <10k faces.  In this particular case, you are almost 4x those counts.

To help me better understand your situation, what are you aiming to use the lower resolution target mesh for?  ex: games, film, 3d printing, selling as a 3d model, etc.  We have had a few 1 star ratings show up recently on the Blender Market, and I'm wondering if these are from artists who are having a similar experience to you, because we haven't specifically optimized RF for your/their workflow and context.

Again, thank you for submitting this issue and sharing your .blend file!  This will help guide our future updates!

**Comment by Lewiatan45** [comment]
How can you sell your plugin for 86$ and expect people to use it _only_ for high poly meshes that are lower than 1m triangles and low poly that are below 10k? There is nowhere said your Blanderartist page this plugin does not support high poly meshes retopology at all. I know personally several people who were looking for a plugin just for what I had been doing. 

I use your plugin to retopo high poly meshes and then use low poly mesh for 3D animation. I bet people who gave you 1 star wanted to do a retopology of models of the caliber I showed you in the blend file. Like someone said, if your plugin can only be efficient at the high resolution source meshes that are <1m triangles and the low resolution target mesh is <10k faces, then at this point people can use shrinkwrap setup instead. 
At this point, I may give 1-star rating for this plugin and stop recommending it as well because you will not fix this within a year considering how long it took to get this version to be released. 

Yes, I am irritated.

**Comment by jlampel** [comment]
We will continue working on improving performance, and I'm closing this out because it's not pointing out a specific way in which we can practically do that. Decimating the mesh slightly before retopology to be under 1M polys is standard practice for other non-ZBrush apps like Maya, is suggested anyway by the industry artists we've talked to, takes about a minute or less to do, and will not change the quality of the resulting retopology.
