### ISSUE TITLE
[QUESTION] manual install issues about v3.0.0

### ISSUE THREAD

**Issue by camtofu** [CGCookie/retopoflow#903]
Retopoflow Version: {3.0.0}

Blender Version/Hash: {2.91.0 Win64}

Platform Version/Distribution: {Windows 10 x64 Home Editon}

&nbsp;

I use a portable Blender install on my Windows PC, so I always manually install addons to ensure the installed addons are also portable. On RetopoFlow releases page (https://github.com/CGCookie/retopoflow/releases), I got 2 files to try:
RetopoFlow_v3.00.0.zip
retopoflow-3.0.0.zip (Source code zip)
I extracted above files to Blender addon dir and found issues below:
#1. Both file cannot be enabled when installed in "[Blender_dir]\2.91\scripts\addon_contrib", though it can be listed in Preferences >Addons >Testing. Trying to enable the addon halt Blender.
#2. In file "RetopoFlow_v3.00.0.zip", duplicate file name was found "Contours_32.png" and "contours_32.png" when extracting .zip file.
#3. Under file "retopoflow-3.0.0.zip" (source code zip), the "." in dir name "retopoflow-3.0.0" is illegal due to a known limitation of Blender (https://developer.blender.org/T50042). Trying to enable addon cause failure and give error message:

> Traceback (most recent call last):
>   File "Z:\blender_2.91\2.91\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
> ModuleNotFoundError: No module named 'retopoflow-3.0.0'
>

**Comment by vxlcoder** [comment]
Thanks for the report, @camtofu.

I haven't fully tested installing RF to be fully portable, but I believe the following details should be correct.  I'll try to answer each item you listed.

1. I haven't tested installing under `2.91/scripts/addon_contrib`.  It _should_ work under `2.91/scripts/addons`.  Will test installing under other folders when I get a chance.
2. This is an oversight.  Default Windows is not case sensitive, so it sees `Contours_32.png` and `contours_32.png` as the same file, even though it isn't.  As far as RF goes, this actually isn't a problem, because I believe only `contours-icon.png` is used.  This means that you _should_ be able to ignore this issue or delete one of the `*ontours_32.png` files, and everything should work just fine.  Will clean up that icons folder.
3. The source code zip is not a Blender installable zip.  The release zip or the file that we package on the [Blender Market](https://blendermarket.com/products/retopoflow) is structured correctly to be installed using Blender's add-on install button.

I'd recommend using the Blender addon install button to install either the [latest release zip](https://github.com/CGCookie/retopoflow/releases/tag/v3.00.0) or the one on the [Blender Market](https://blendermarket.com/products/retopoflow), but setting the `Target Path` (see image below) to `Default`.  This _should_ install the add-on into the `2.91/scripts/addons` so that it is portable.

![image](https://user-images.githubusercontent.com/3790699/100740658-10d6ce00-33a7-11eb-987b-a4a68ed304f5.png)

**Comment by camtofu** [comment]
Thanks for quick reply, @vxlcoder.

Your answer to item 3 is a useful tip for me..

**Comment by vxlcoder** [comment]
good to hear!

if this solved your issue, please go ahead and close this issue.  if not, let us know.

have a great day!

**Comment by camtofu** [comment]
Frankly, not supporting "addons_contrib" dir still seems a problem.  RF is the first and only addon that I found not supporting "addons_contrib" dir among hundred plus.
According to Blender wiki, the dir "addons_contrib" is legal position for running addons. 
https://wiki.blender.org/wiki/Process/Addons
> They can be found in these two directories of the main Blender repository:
> release/scripts/addons
> release/scripts/addons_contrib
From my personal experience, "addons_contrib" dir is quite handy for testing beta phase or newly got addons. 

BTW, file name "RetopoFlow_v3.00.0.zip" looks a typo. It should be "RetopoFlow_v3.0.0.zip", if you are following Semantic Versioning scheme (https://semver.org/). Leanding zero, or zero fill, is not allowed in versioning number for its misleading.

> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

**Comment by vxlcoder** [comment]
You're right that RF should work with `addons_contrib`.  That was something we missed in our tests.  Will take a look at it as soon as I have a moment to.

**Comment by vxlcoder** [comment]
@camtofu, RF should now work just fine if installed in `addons_contrib` folder (see commit 7a56a88, or wait for next release)

closing this issue now
