### ISSUE TITLE
selection tool?

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#909]
selection is still very tricky.

each tool thinks about selection based on the type of geometry it creates (contours/loops: edge loops, polystrips: faces, polypen: verts/edges/faces, patches/strokes: edges).

also, verts just below the surface of source (thin surface, overlapping surfaces, unsnapped verts, etc.) are very hard to select.  also edges and faces become impossible select because they depend on vert visibility.

could we create a selection tool that's much more "graceful" and customizable?  this would allow each tool to continue its focus on what it works on, but the artist can still select geometry easily?

**Comment by jlampel** [comment]
This got me thinking! One of the most common things to want to do in retopology at any stage in the process is push vertices around. While switching tools is much faster now thanks to the pie menu, it can be a bit flow-breaking to have to switch to the PolyPen or Tweak tool and back just to shift a vertex up a little bit after completing a stroke or a strip. It's happened often enough that I want to move something, but since I'm in the wrong tool, I accidentally end up moving a whole edge and it makes it worse. 

I think a selection tool on steroids could be a solution that could help speed things up quite a bit, but it would require a some larger changes. Here's what I'd love to try:

	• LMB click
		○  All non-brush tools
			§ Select verts, edges, or faces 
	• LMB drag
		○ Selection Tool
			§ Either tweak, box , paint, or lasso select depending on what it's set to 
		○ Contours and Loops
			§ Grab and slide if only edges are selected
			§ Tweak if faces or disconnected vertices are selected
		○ PolyStrips, Strokes, Patches, PolyPen
			§ Tweak
	• LMB Shift drag
		○ All non-brush tools
			§ Paint select
	• LMB Ctrl Shift click
		○ All non-brush tools
			§ Select shortest path

So if all tools are able to select verts, edges, and faces, where would a selection tool come in handy? If it were also a context sensitive multi-purpose tool. Imagine one tool that behaved like this: 

	• LMB click: Select verts, edges, or faces 
	• LMB drag: Either tweak, box , paint, or lasso select depending on what it's set to 
	• LMB Ctrl click: Place a PolyPen point
	• LMB Ctrl drag from a face: Create a PolyStrip, with the size set to the size of the face dragged from. Handles are only shown immediately after creation before selection changes
	• LMB Ctrl drag from outside of the source object: Create a Contours cut
	• LMB Ctrl drag inside the source object and not from a face: Create a Stroke
	• F: Create a patch
	• Ctrl+R: Add a loop cut

I'm sure there would be all sorts of conflicts initially (what happens to PP place and drag functionality, how is Strokes brush size determined, etc.), but if we determine what should take priority in certain scenarios, it could be a tool that I'd use 90% of the time. It's interesting that Jay, myself, Daniel Bystedt, and the Flipped Normals guys seem to settle on generally using the same tools in the same situations, and I think this context-aware selection tool could put all of the most important parts of each one within reach. 

Would something like that be possible or would there be too many tradeoffs?

**Comment by TakUser** [comment]
Adding to the issues with selection, but sometimes when making a selection and moving it; especially with the PolyPen tool, the selection gets stuck to the mouse and multiple clicks need to be made before the position changes to the selection are applied.  I'm using the latest GitHub release of Retopoflow in this instance.

**Comment by vxlcoder** [comment]
thanks for the additional info, @TakUser.

could you record a video of this happening? this seems like a new issue that I haven't seen?

or, if you can give instructions for reproducing this bug on a default cube(so I can replicate), that would be great too!

**Comment by TakUser** [comment]
> thanks for the additional info, @TakUser.
> 
> could you record a video of this happening? this seems like a new issue that I haven't seen?
> 
> or, if you can give instructions for reproducing this bug on a default cube(so I can replicate), that would be great too!

Is there a way to screencast blender with keys pressed along with mouseclicks?

**Comment by jlampel** [comment]
Implemented in 3.4!
