### ISSUE TITLE
Target mesh barely visible

### ISSUE THREAD

**Issue by noemikr** [CGCookie/retopoflow#968]
Please prefix your issue name with one of the following:  **[QUESTION]**

Retopoflow Version: 3.0

Blender Version/Hash: Blender 2.91.2

The newly created strokes and target mesh are barely visible, they are crashing through the source mesh. Is there a way to solve this?
![Screenshot (1)](https://user-images.githubusercontent.com/79841082/109486456-3006f980-7a83-11eb-9eec-fd2ed9a537ce.jpg)

**Comment by vxlcoder** [comment]
thanks for the question @noemikr.

RetopoFlow draws the target differently based on how it interacts with the source mesh, whether it is on the surface of target, under the surface, on the backside of the target, etc. you can adjust how this visualization looks by adjusting the individual alpha values (which controls how visible/invisible the target appears).

options > display > individual alpha values > ...

note: orthographic and perspective projection will have a different look, because they project the geometry differently.

as for crashing through: the source mesh (sphere) has a high curvature/details, and the target can only capture this curvature/detail at the vertices. if you want to better capture the high curvature, you will need to increase the density of target (create more vertices and faces).

flat areas can be captured with small number of vertices.

high detail areas require more.

I hope I've answered your questions. please let me know if you have any follow up questions or if you need more details.

have a great day!

**Comment by vxlcoder** [comment]
did the suggestions above help this issue, @noemikr, or do you have more questions/issues with the visualizations?
