### ISSUE TITLE
[BUG] PolyPen preview does not always appear when holding Ctrl

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#974]
I've noticed this behavior off and on but have yet to find a way to replicate it. Sometimes when using PP the green preview lines stop showing up, and then after a little while they start working again. A user mentioned it happening to them this morning so it must still be happening in 3.1.0. I'll report back if I can get it to happen again.

**Comment by JimbobweSmells** [comment]
I just picked up RetopoFlow and it's been happening every odd minute or so, seemingly at random, before occasionally appearing again.

**Comment by vxlcoder** [comment]
thanks for the confirmation, @JimbobweSmells!

Would you mind running a test for us?

Use RetopoFlow's Updater to try the latest `v3.1.1` branch to see if it has the same issue.  see https://docs.retopoflow.com/addon_updater.html for steps.  You will need to type `v3.1.1` into the `Advanced: Commit / Branch` box.

**Comment by JimbobweSmells** [comment]
I tried the update process as you described however after the installation and restarting, the RetopoFlow UI ceased to work and I had to remove the RetopoFlow installation and reinstall the previous version.
I also attempted a manual install but it gave me a callback on load.
[image](https://user-images.githubusercontent.com/80879675/122313819-c5f85000-cecb-11eb-89e2-c46f76772ff5.png)

I tried with version 2.9 instead of the latest, but RetopoFlows UI wouldn't load once again, and having redownloaded the latest it's also not showing up... I think my Blender install might be borked up, so I am going to try a fresh install.

**Comment by JimbobweSmells** [comment]
> I tried with version 2.9 instead of the latest, but RetopoFlows UI wouldn't load once again, and having redownloaded the latest it's also not showing up... I think my Blender install might be borked up, so I am going to try a fresh install.

After a fresh install things work again but I still have the problems with downloading 3.1.1, and there's been no change to the PolyPen preview.

**Comment by jfranmatheu** [comment]
Can't replicate under RF 3.4.4 and Blender 4.3. Closing issue due to prolonged inactivity. If the issue persists, please reopen it. Thank you!
