### ISSUE TITLE
Question: Cannot Install Retopoflow 3.1.0

### ISSUE THREAD

**Issue by fmb501** [CGCookie/retopoflow#991]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.1.0

Blender Version/Hash: 2.92

Platform Version/Distribution: Windows 10

&nbsp;

**Issue:**

I have used Retopoflow since you introduced it. but I haven't used it recently.  I noticed at the top of my Blender 2.92 viewport that Retopoflow was broken and so I downloaded the recent version from BlenderMarket, deleted the old version and installed version 3.1.0 and activated it.

But Retopoflow no longer shows up at the top of my Viewport and there is no indication where I can access it either in EEVE or CYCLES.

I've removed it and reinstalled it a number of times.  I've downloaded the most current version from Blender Market but no joy.

I've read the documentation but I don't see anything I'm doing wrong.

Any ideas why it appears in the Preferences that it's is working but no longer appears at the top of the Viewport.

I do use Workspace to customize each of the modes such as Layoout, Modeling, etc. so only those addons I need for each mode are on the vertical tabs on the left.  Otherwise, it's a complete mess when they all show up on every mode.

Thanks
BMFVet

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Thanks for the report, @fmb501.

Sorry that you're having issues.

I'm not sure what the issue is, so let's try a few things if you're willing to help debug.

Test 1: Open the system console when you're in Blender and have the RetopoFlow add-on enabled in Prefs using Windows > Toggle System Console.  Then, copy all the text you see in the console and paste it here as a reply.  Also, can you include a screenshot of Blender's main window using the Print Screen button?

Test 2: Have you tried Blender's Load Factory Settings, then reinstall and enable RetopoFlow?  We haven't extensively tested RF using really customized workspaces, but that _should not_ matter, as RF _should_ work in any 3D View.

Note: RF does not work well when there are multiple 3D Views (in different areas/spaces within a window, using quad view, or different windows), but this doesn't sound like the issue you're having now.

Thanks for helping us with debugging this issue!

**Comment by fmb501** [comment]
Never mind.  My custom startup viewport doesn't have any objects in it because I like to start clean.  I didn't realize that RetopoFlow needed an object for it to activate in the Viewport until I added a cube to start a new model and realized RetopoFlow only activates when there is an object.

My apologies for the inconvenience.  Great product.

**Comment by vxlcoder** [comment]
great! let us know if you have other issues. happy retopoing!
